package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class CfgPageModule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.module_id
     *
     * @mbg.generated
     */
    private String moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.page_id
     *
     * @mbg.generated
     */
    private String pageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.type
     *
     * @mbg.generated
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.row
     *
     * @mbg.generated
     */
    private Short row;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.col
     *
     * @mbg.generated
     */
    private Short col;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.alias
     *
     * @mbg.generated
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.width
     *
     * @mbg.generated
     */
    private Short width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.sort
     *
     * @mbg.generated
     */
    private Long sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_page_module.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cfg_page_module
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.id
     *
     * @return the value of cfg_page_module.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.id
     *
     * @param id the value for cfg_page_module.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.module_id
     *
     * @return the value of cfg_page_module.module_id
     *
     * @mbg.generated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.module_id
     *
     * @param moduleId the value for cfg_page_module.module_id
     *
     * @mbg.generated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.page_id
     *
     * @return the value of cfg_page_module.page_id
     *
     * @mbg.generated
     */
    public String getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.page_id
     *
     * @param pageId the value for cfg_page_module.page_id
     *
     * @mbg.generated
     */
    public void setPageId(String pageId) {
        this.pageId = pageId == null ? null : pageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.type
     *
     * @return the value of cfg_page_module.type
     *
     * @mbg.generated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.type
     *
     * @param type the value for cfg_page_module.type
     *
     * @mbg.generated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.row
     *
     * @return the value of cfg_page_module.row
     *
     * @mbg.generated
     */
    public Short getRow() {
        return row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.row
     *
     * @param row the value for cfg_page_module.row
     *
     * @mbg.generated
     */
    public void setRow(Short row) {
        this.row = row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.col
     *
     * @return the value of cfg_page_module.col
     *
     * @mbg.generated
     */
    public Short getCol() {
        return col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.col
     *
     * @param col the value for cfg_page_module.col
     *
     * @mbg.generated
     */
    public void setCol(Short col) {
        this.col = col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.alias
     *
     * @return the value of cfg_page_module.alias
     *
     * @mbg.generated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.alias
     *
     * @param alias the value for cfg_page_module.alias
     *
     * @mbg.generated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.width
     *
     * @return the value of cfg_page_module.width
     *
     * @mbg.generated
     */
    public Short getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.width
     *
     * @param width the value for cfg_page_module.width
     *
     * @mbg.generated
     */
    public void setWidth(Short width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.sort
     *
     * @return the value of cfg_page_module.sort
     *
     * @mbg.generated
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.sort
     *
     * @param sort the value for cfg_page_module.sort
     *
     * @mbg.generated
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_page_module.create_date
     *
     * @return the value of cfg_page_module.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_page_module.create_date
     *
     * @param createDate the value for cfg_page_module.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_page_module
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", moduleId=").append(moduleId);
        sb.append(", pageId=").append(pageId);
        sb.append(", type=").append(type);
        sb.append(", row=").append(row);
        sb.append(", col=").append(col);
        sb.append(", alias=").append(alias);
        sb.append(", width=").append(width);
        sb.append(", sort=").append(sort);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}