package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class GenTable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.parent_table
     *
     * @mbg.generated
     */
    private String parentTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.parent_table_fk
     *
     * @mbg.generated
     */
    private String parentTableFk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.id
     *
     * @return the value of gen_table.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.id
     *
     * @param id the value for gen_table.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.name
     *
     * @return the value of gen_table.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.name
     *
     * @param name the value for gen_table.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.comments
     *
     * @return the value of gen_table.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.comments
     *
     * @param comments the value for gen_table.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.class_name
     *
     * @return the value of gen_table.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.class_name
     *
     * @param className the value for gen_table.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.parent_table
     *
     * @return the value of gen_table.parent_table
     *
     * @mbg.generated
     */
    public String getParentTable() {
        return parentTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.parent_table
     *
     * @param parentTable the value for gen_table.parent_table
     *
     * @mbg.generated
     */
    public void setParentTable(String parentTable) {
        this.parentTable = parentTable == null ? null : parentTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.parent_table_fk
     *
     * @return the value of gen_table.parent_table_fk
     *
     * @mbg.generated
     */
    public String getParentTableFk() {
        return parentTableFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.parent_table_fk
     *
     * @param parentTableFk the value for gen_table.parent_table_fk
     *
     * @mbg.generated
     */
    public void setParentTableFk(String parentTableFk) {
        this.parentTableFk = parentTableFk == null ? null : parentTableFk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.create_by
     *
     * @return the value of gen_table.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.create_by
     *
     * @param createBy the value for gen_table.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.create_date
     *
     * @return the value of gen_table.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.create_date
     *
     * @param createDate the value for gen_table.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.update_by
     *
     * @return the value of gen_table.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.update_by
     *
     * @param updateBy the value for gen_table.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.update_date
     *
     * @return the value of gen_table.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.update_date
     *
     * @param updateDate the value for gen_table.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.remarks
     *
     * @return the value of gen_table.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.remarks
     *
     * @param remarks the value for gen_table.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.del_flag
     *
     * @return the value of gen_table.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.del_flag
     *
     * @param delFlag the value for gen_table.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", comments=").append(comments);
        sb.append(", className=").append(className);
        sb.append(", parentTable=").append(parentTable);
        sb.append(", parentTableFk=").append(parentTableFk);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}