package com.example.springboot.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class HzAbility implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_ability.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_ability.ability_name
     *
     * @mbg.generated
     */
    private String abilityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_ability.ability_value
     *
     * @mbg.generated
     */
    private BigDecimal abilityValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_ability.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_ability.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_ability
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_ability.id
     *
     * @return the value of hz_ability.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_ability.id
     *
     * @param id the value for hz_ability.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_ability.ability_name
     *
     * @return the value of hz_ability.ability_name
     *
     * @mbg.generated
     */
    public String getAbilityName() {
        return abilityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_ability.ability_name
     *
     * @param abilityName the value for hz_ability.ability_name
     *
     * @mbg.generated
     */
    public void setAbilityName(String abilityName) {
        this.abilityName = abilityName == null ? null : abilityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_ability.ability_value
     *
     * @return the value of hz_ability.ability_value
     *
     * @mbg.generated
     */
    public BigDecimal getAbilityValue() {
        return abilityValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_ability.ability_value
     *
     * @param abilityValue the value for hz_ability.ability_value
     *
     * @mbg.generated
     */
    public void setAbilityValue(BigDecimal abilityValue) {
        this.abilityValue = abilityValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_ability.create_time
     *
     * @return the value of hz_ability.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_ability.create_time
     *
     * @param createTime the value for hz_ability.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_ability.sort
     *
     * @return the value of hz_ability.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_ability.sort
     *
     * @param sort the value for hz_ability.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_ability
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", abilityName=").append(abilityName);
        sb.append(", abilityValue=").append(abilityValue);
        sb.append(", createTime=").append(createTime);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}