package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class HzApplyPersonalVm implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.apply_id
     *
     * @mbg.generated
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.test_id
     *
     * @mbg.generated
     */
    private String testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.network_id
     *
     * @mbg.generated
     */
    private String networkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.vm_id
     *
     * @mbg.generated
     */
    private String vmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.is_install
     *
     * @mbg.generated
     */
    private Long isInstall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.template_name
     *
     * @mbg.generated
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_personal_vm.template_id
     *
     * @mbg.generated
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_apply_personal_vm
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.id
     *
     * @return the value of hz_apply_personal_vm.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.id
     *
     * @param id the value for hz_apply_personal_vm.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.user_id
     *
     * @return the value of hz_apply_personal_vm.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.user_id
     *
     * @param userId the value for hz_apply_personal_vm.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.apply_id
     *
     * @return the value of hz_apply_personal_vm.apply_id
     *
     * @mbg.generated
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.apply_id
     *
     * @param applyId the value for hz_apply_personal_vm.apply_id
     *
     * @mbg.generated
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.test_id
     *
     * @return the value of hz_apply_personal_vm.test_id
     *
     * @mbg.generated
     */
    public String getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.test_id
     *
     * @param testId the value for hz_apply_personal_vm.test_id
     *
     * @mbg.generated
     */
    public void setTestId(String testId) {
        this.testId = testId == null ? null : testId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.network_id
     *
     * @return the value of hz_apply_personal_vm.network_id
     *
     * @mbg.generated
     */
    public String getNetworkId() {
        return networkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.network_id
     *
     * @param networkId the value for hz_apply_personal_vm.network_id
     *
     * @mbg.generated
     */
    public void setNetworkId(String networkId) {
        this.networkId = networkId == null ? null : networkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.vm_id
     *
     * @return the value of hz_apply_personal_vm.vm_id
     *
     * @mbg.generated
     */
    public String getVmId() {
        return vmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.vm_id
     *
     * @param vmId the value for hz_apply_personal_vm.vm_id
     *
     * @mbg.generated
     */
    public void setVmId(String vmId) {
        this.vmId = vmId == null ? null : vmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.start_time
     *
     * @return the value of hz_apply_personal_vm.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.start_time
     *
     * @param startTime the value for hz_apply_personal_vm.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.is_install
     *
     * @return the value of hz_apply_personal_vm.is_install
     *
     * @mbg.generated
     */
    public Long getIsInstall() {
        return isInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.is_install
     *
     * @param isInstall the value for hz_apply_personal_vm.is_install
     *
     * @mbg.generated
     */
    public void setIsInstall(Long isInstall) {
        this.isInstall = isInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.template_name
     *
     * @return the value of hz_apply_personal_vm.template_name
     *
     * @mbg.generated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.template_name
     *
     * @param templateName the value for hz_apply_personal_vm.template_name
     *
     * @mbg.generated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_personal_vm.template_id
     *
     * @return the value of hz_apply_personal_vm.template_id
     *
     * @mbg.generated
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_personal_vm.template_id
     *
     * @param templateId the value for hz_apply_personal_vm.template_id
     *
     * @mbg.generated
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_apply_personal_vm
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", applyId=").append(applyId);
        sb.append(", testId=").append(testId);
        sb.append(", networkId=").append(networkId);
        sb.append(", vmId=").append(vmId);
        sb.append(", startTime=").append(startTime);
        sb.append(", isInstall=").append(isInstall);
        sb.append(", templateName=").append(templateName);
        sb.append(", templateId=").append(templateId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}