package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class HzApplyDelay implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_delay.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_delay.apply_id
     *
     * @mbg.generated
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_delay.delay_time
     *
     * @mbg.generated
     */
    private Integer delayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_delay.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_delay.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_apply_delay.is_cancel
     *
     * @mbg.generated
     */
    private Integer isCancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_apply_delay
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_delay.id
     *
     * @return the value of hz_apply_delay.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_delay.id
     *
     * @param id the value for hz_apply_delay.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_delay.apply_id
     *
     * @return the value of hz_apply_delay.apply_id
     *
     * @mbg.generated
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_delay.apply_id
     *
     * @param applyId the value for hz_apply_delay.apply_id
     *
     * @mbg.generated
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_delay.delay_time
     *
     * @return the value of hz_apply_delay.delay_time
     *
     * @mbg.generated
     */
    public Integer getDelayTime() {
        return delayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_delay.delay_time
     *
     * @param delayTime the value for hz_apply_delay.delay_time
     *
     * @mbg.generated
     */
    public void setDelayTime(Integer delayTime) {
        this.delayTime = delayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_delay.create_time
     *
     * @return the value of hz_apply_delay.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_delay.create_time
     *
     * @param createTime the value for hz_apply_delay.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_delay.create_user
     *
     * @return the value of hz_apply_delay.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_delay.create_user
     *
     * @param createUser the value for hz_apply_delay.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_apply_delay.is_cancel
     *
     * @return the value of hz_apply_delay.is_cancel
     *
     * @mbg.generated
     */
    public Integer getIsCancel() {
        return isCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_apply_delay.is_cancel
     *
     * @param isCancel the value for hz_apply_delay.is_cancel
     *
     * @mbg.generated
     */
    public void setIsCancel(Integer isCancel) {
        this.isCancel = isCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_apply_delay
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", applyId=").append(applyId);
        sb.append(", delayTime=").append(delayTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", isCancel=").append(isCancel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}