package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class HzCalendar implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.resource_id
     *
     * @mbg.generated
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.classroom_id
     *
     * @mbg.generated
     */
    private String classroomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.open_date
     *
     * @mbg.generated
     */
    private Date openDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.is_open
     *
     * @mbg.generated
     */
    private Integer isOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.last_update_time
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.updator_id
     *
     * @mbg.generated
     */
    private String updatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.updator_name
     *
     * @mbg.generated
     */
    private String updatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_calendar.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_calendar
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.resource_id
     *
     * @return the value of hz_calendar.resource_id
     *
     * @mbg.generated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.resource_id
     *
     * @param resourceId the value for hz_calendar.resource_id
     *
     * @mbg.generated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.classroom_id
     *
     * @return the value of hz_calendar.classroom_id
     *
     * @mbg.generated
     */
    public String getClassroomId() {
        return classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.classroom_id
     *
     * @param classroomId the value for hz_calendar.classroom_id
     *
     * @mbg.generated
     */
    public void setClassroomId(String classroomId) {
        this.classroomId = classroomId == null ? null : classroomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.open_date
     *
     * @return the value of hz_calendar.open_date
     *
     * @mbg.generated
     */
    public Date getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.open_date
     *
     * @param openDate the value for hz_calendar.open_date
     *
     * @mbg.generated
     */
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.is_open
     *
     * @return the value of hz_calendar.is_open
     *
     * @mbg.generated
     */
    public Integer getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.is_open
     *
     * @param isOpen the value for hz_calendar.is_open
     *
     * @mbg.generated
     */
    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.create_time
     *
     * @return the value of hz_calendar.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.create_time
     *
     * @param createTime the value for hz_calendar.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.creator_id
     *
     * @return the value of hz_calendar.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.creator_id
     *
     * @param creatorId the value for hz_calendar.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.creator_name
     *
     * @return the value of hz_calendar.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.creator_name
     *
     * @param creatorName the value for hz_calendar.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.last_update_time
     *
     * @return the value of hz_calendar.last_update_time
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.last_update_time
     *
     * @param lastUpdateTime the value for hz_calendar.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.updator_id
     *
     * @return the value of hz_calendar.updator_id
     *
     * @mbg.generated
     */
    public String getUpdatorId() {
        return updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.updator_id
     *
     * @param updatorId the value for hz_calendar.updator_id
     *
     * @mbg.generated
     */
    public void setUpdatorId(String updatorId) {
        this.updatorId = updatorId == null ? null : updatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.updator_name
     *
     * @return the value of hz_calendar.updator_name
     *
     * @mbg.generated
     */
    public String getUpdatorName() {
        return updatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.updator_name
     *
     * @param updatorName the value for hz_calendar.updator_name
     *
     * @mbg.generated
     */
    public void setUpdatorName(String updatorName) {
        this.updatorName = updatorName == null ? null : updatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_calendar.is_delete
     *
     * @return the value of hz_calendar.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_calendar.is_delete
     *
     * @param isDelete the value for hz_calendar.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_calendar
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resourceId=").append(resourceId);
        sb.append(", classroomId=").append(classroomId);
        sb.append(", openDate=").append(openDate);
        sb.append(", isOpen=").append(isOpen);
        sb.append(", createTime=").append(createTime);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", creatorName=").append(creatorName);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", updatorId=").append(updatorId);
        sb.append(", updatorName=").append(updatorName);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}