package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class HzCourseware implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.time
     *
     * @mbg.generated
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.res_id
     *
     * @mbg.generated
     */
    private String resId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.file_url
     *
     * @mbg.generated
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.file_suffix
     *
     * @mbg.generated
     */
    private String fileSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.file_size
     *
     * @mbg.generated
     */
    private Long fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.converted_url
     *
     * @mbg.generated
     */
    private String convertedUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.res_type
     *
     * @mbg.generated
     */
    private Integer resType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_courseware.use_type
     *
     * @mbg.generated
     */
    private Integer useType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_courseware
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.id
     *
     * @return the value of hz_courseware.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.id
     *
     * @param id the value for hz_courseware.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.name
     *
     * @return the value of hz_courseware.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.name
     *
     * @param name the value for hz_courseware.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.type
     *
     * @return the value of hz_courseware.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.type
     *
     * @param type the value for hz_courseware.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.time
     *
     * @return the value of hz_courseware.time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.time
     *
     * @param time the value for hz_courseware.time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.res_id
     *
     * @return the value of hz_courseware.res_id
     *
     * @mbg.generated
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.res_id
     *
     * @param resId the value for hz_courseware.res_id
     *
     * @mbg.generated
     */
    public void setResId(String resId) {
        this.resId = resId == null ? null : resId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.file_url
     *
     * @return the value of hz_courseware.file_url
     *
     * @mbg.generated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.file_url
     *
     * @param fileUrl the value for hz_courseware.file_url
     *
     * @mbg.generated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.create_time
     *
     * @return the value of hz_courseware.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.create_time
     *
     * @param createTime the value for hz_courseware.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.creator_id
     *
     * @return the value of hz_courseware.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.creator_id
     *
     * @param creatorId the value for hz_courseware.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.file_suffix
     *
     * @return the value of hz_courseware.file_suffix
     *
     * @mbg.generated
     */
    public String getFileSuffix() {
        return fileSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.file_suffix
     *
     * @param fileSuffix the value for hz_courseware.file_suffix
     *
     * @mbg.generated
     */
    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix == null ? null : fileSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.file_size
     *
     * @return the value of hz_courseware.file_size
     *
     * @mbg.generated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.file_size
     *
     * @param fileSize the value for hz_courseware.file_size
     *
     * @mbg.generated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.converted_url
     *
     * @return the value of hz_courseware.converted_url
     *
     * @mbg.generated
     */
    public String getConvertedUrl() {
        return convertedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.converted_url
     *
     * @param convertedUrl the value for hz_courseware.converted_url
     *
     * @mbg.generated
     */
    public void setConvertedUrl(String convertedUrl) {
        this.convertedUrl = convertedUrl == null ? null : convertedUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.res_type
     *
     * @return the value of hz_courseware.res_type
     *
     * @mbg.generated
     */
    public Integer getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.res_type
     *
     * @param resType the value for hz_courseware.res_type
     *
     * @mbg.generated
     */
    public void setResType(Integer resType) {
        this.resType = resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_courseware.use_type
     *
     * @return the value of hz_courseware.use_type
     *
     * @mbg.generated
     */
    public Integer getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_courseware.use_type
     *
     * @param useType the value for hz_courseware.use_type
     *
     * @mbg.generated
     */
    public void setUseType(Integer useType) {
        this.useType = useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_courseware
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", time=").append(time);
        sb.append(", resId=").append(resId);
        sb.append(", fileUrl=").append(fileUrl);
        sb.append(", createTime=").append(createTime);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", fileSuffix=").append(fileSuffix);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", convertedUrl=").append(convertedUrl);
        sb.append(", resType=").append(resType);
        sb.append(", useType=").append(useType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}