package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class HzExamPaper implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.test_ids
     *
     * @mbg.generated
     */
    private String testIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_exam_paper.score_config
     *
     * @mbg.generated
     */
    private String scoreConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_exam_paper
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.id
     *
     * @return the value of hz_exam_paper.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.id
     *
     * @param id the value for hz_exam_paper.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.name
     *
     * @return the value of hz_exam_paper.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.name
     *
     * @param name the value for hz_exam_paper.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.course_id
     *
     * @return the value of hz_exam_paper.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.course_id
     *
     * @param courseId the value for hz_exam_paper.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.test_ids
     *
     * @return the value of hz_exam_paper.test_ids
     *
     * @mbg.generated
     */
    public String getTestIds() {
        return testIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.test_ids
     *
     * @param testIds the value for hz_exam_paper.test_ids
     *
     * @mbg.generated
     */
    public void setTestIds(String testIds) {
        this.testIds = testIds == null ? null : testIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.creator_id
     *
     * @return the value of hz_exam_paper.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.creator_id
     *
     * @param creatorId the value for hz_exam_paper.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.creator_name
     *
     * @return the value of hz_exam_paper.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.creator_name
     *
     * @param creatorName the value for hz_exam_paper.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.create_time
     *
     * @return the value of hz_exam_paper.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.create_time
     *
     * @param createTime the value for hz_exam_paper.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.is_delete
     *
     * @return the value of hz_exam_paper.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.is_delete
     *
     * @param isDelete the value for hz_exam_paper.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.state
     *
     * @return the value of hz_exam_paper.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.state
     *
     * @param state the value for hz_exam_paper.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.score
     *
     * @return the value of hz_exam_paper.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.score
     *
     * @param score the value for hz_exam_paper.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_exam_paper.score_config
     *
     * @return the value of hz_exam_paper.score_config
     *
     * @mbg.generated
     */
    public String getScoreConfig() {
        return scoreConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_exam_paper.score_config
     *
     * @param scoreConfig the value for hz_exam_paper.score_config
     *
     * @mbg.generated
     */
    public void setScoreConfig(String scoreConfig) {
        this.scoreConfig = scoreConfig == null ? null : scoreConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_exam_paper
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", courseId=").append(courseId);
        sb.append(", testIds=").append(testIds);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", creatorName=").append(creatorName);
        sb.append(", createTime=").append(createTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", state=").append(state);
        sb.append(", score=").append(score);
        sb.append(", scoreConfig=").append(scoreConfig);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}