package com.example.springboot.pojo;

import java.io.Serializable;

public class HzHyperNetwork implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_network.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_network.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_network.binding_id
     *
     * @mbg.generated
     */
    private String bindingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_network.binding_type
     *
     * @mbg.generated
     */
    private Integer bindingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_network.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_network.public_ip
     *
     * @mbg.generated
     */
    private String publicIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_network.public_ip_id
     *
     * @mbg.generated
     */
    private String publicIpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_hyper_network
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_network.id
     *
     * @return the value of hz_hyper_network.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_network.id
     *
     * @param id the value for hz_hyper_network.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_network.name
     *
     * @return the value of hz_hyper_network.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_network.name
     *
     * @param name the value for hz_hyper_network.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_network.binding_id
     *
     * @return the value of hz_hyper_network.binding_id
     *
     * @mbg.generated
     */
    public String getBindingId() {
        return bindingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_network.binding_id
     *
     * @param bindingId the value for hz_hyper_network.binding_id
     *
     * @mbg.generated
     */
    public void setBindingId(String bindingId) {
        this.bindingId = bindingId == null ? null : bindingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_network.binding_type
     *
     * @return the value of hz_hyper_network.binding_type
     *
     * @mbg.generated
     */
    public Integer getBindingType() {
        return bindingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_network.binding_type
     *
     * @param bindingType the value for hz_hyper_network.binding_type
     *
     * @mbg.generated
     */
    public void setBindingType(Integer bindingType) {
        this.bindingType = bindingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_network.type
     *
     * @return the value of hz_hyper_network.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_network.type
     *
     * @param type the value for hz_hyper_network.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_network.public_ip
     *
     * @return the value of hz_hyper_network.public_ip
     *
     * @mbg.generated
     */
    public String getPublicIp() {
        return publicIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_network.public_ip
     *
     * @param publicIp the value for hz_hyper_network.public_ip
     *
     * @mbg.generated
     */
    public void setPublicIp(String publicIp) {
        this.publicIp = publicIp == null ? null : publicIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_network.public_ip_id
     *
     * @return the value of hz_hyper_network.public_ip_id
     *
     * @mbg.generated
     */
    public String getPublicIpId() {
        return publicIpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_network.public_ip_id
     *
     * @param publicIpId the value for hz_hyper_network.public_ip_id
     *
     * @mbg.generated
     */
    public void setPublicIpId(String publicIpId) {
        this.publicIpId = publicIpId == null ? null : publicIpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_hyper_network
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", bindingId=").append(bindingId);
        sb.append(", bindingType=").append(bindingType);
        sb.append(", type=").append(type);
        sb.append(", publicIp=").append(publicIp);
        sb.append(", publicIpId=").append(publicIpId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}