package com.example.springboot.pojo;

import java.io.Serializable;

public class HzHyperPortrule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_portrule.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_portrule.vm_id
     *
     * @mbg.generated
     */
    private String vmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_portrule.private_ip
     *
     * @mbg.generated
     */
    private String privateIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_portrule.public_ip
     *
     * @mbg.generated
     */
    private String publicIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_portrule.private_port
     *
     * @mbg.generated
     */
    private Integer privatePort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_hyper_portrule.public_port
     *
     * @mbg.generated
     */
    private Integer publicPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_hyper_portrule
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_portrule.id
     *
     * @return the value of hz_hyper_portrule.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_portrule.id
     *
     * @param id the value for hz_hyper_portrule.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_portrule.vm_id
     *
     * @return the value of hz_hyper_portrule.vm_id
     *
     * @mbg.generated
     */
    public String getVmId() {
        return vmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_portrule.vm_id
     *
     * @param vmId the value for hz_hyper_portrule.vm_id
     *
     * @mbg.generated
     */
    public void setVmId(String vmId) {
        this.vmId = vmId == null ? null : vmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_portrule.private_ip
     *
     * @return the value of hz_hyper_portrule.private_ip
     *
     * @mbg.generated
     */
    public String getPrivateIp() {
        return privateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_portrule.private_ip
     *
     * @param privateIp the value for hz_hyper_portrule.private_ip
     *
     * @mbg.generated
     */
    public void setPrivateIp(String privateIp) {
        this.privateIp = privateIp == null ? null : privateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_portrule.public_ip
     *
     * @return the value of hz_hyper_portrule.public_ip
     *
     * @mbg.generated
     */
    public String getPublicIp() {
        return publicIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_portrule.public_ip
     *
     * @param publicIp the value for hz_hyper_portrule.public_ip
     *
     * @mbg.generated
     */
    public void setPublicIp(String publicIp) {
        this.publicIp = publicIp == null ? null : publicIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_portrule.private_port
     *
     * @return the value of hz_hyper_portrule.private_port
     *
     * @mbg.generated
     */
    public Integer getPrivatePort() {
        return privatePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_portrule.private_port
     *
     * @param privatePort the value for hz_hyper_portrule.private_port
     *
     * @mbg.generated
     */
    public void setPrivatePort(Integer privatePort) {
        this.privatePort = privatePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_hyper_portrule.public_port
     *
     * @return the value of hz_hyper_portrule.public_port
     *
     * @mbg.generated
     */
    public Integer getPublicPort() {
        return publicPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_hyper_portrule.public_port
     *
     * @param publicPort the value for hz_hyper_portrule.public_port
     *
     * @mbg.generated
     */
    public void setPublicPort(Integer publicPort) {
        this.publicPort = publicPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_hyper_portrule
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", vmId=").append(vmId);
        sb.append(", privateIp=").append(privateIp);
        sb.append(", publicIp=").append(publicIp);
        sb.append(", privatePort=").append(privatePort);
        sb.append(", publicPort=").append(publicPort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}