package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class HzLabReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.test_id
     *
     * @mbg.generated
     */
    private String testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.test_target
     *
     * @mbg.generated
     */
    private String testTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.test_request
     *
     * @mbg.generated
     */
    private String testRequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.test_environment
     *
     * @mbg.generated
     */
    private String testEnvironment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.test_comment
     *
     * @mbg.generated
     */
    private String testComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.class_id
     *
     * @mbg.generated
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.read_state
     *
     * @mbg.generated
     */
    private Integer readState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.read_time
     *
     * @mbg.generated
     */
    private Date readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.read_name
     *
     * @mbg.generated
     */
    private String readName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.read_comment
     *
     * @mbg.generated
     */
    private String readComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.create_id
     *
     * @mbg.generated
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.create_name
     *
     * @mbg.generated
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.difficult_level
     *
     * @mbg.generated
     */
    private Integer difficultLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.advice
     *
     * @mbg.generated
     */
    private String advice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.back_reason
     *
     * @mbg.generated
     */
    private String backReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.score_state
     *
     * @mbg.generated
     */
    private Integer scoreState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.test_result
     *
     * @mbg.generated
     */
    private String testResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.test_result_html
     *
     * @mbg.generated
     */
    private String testResultHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lab_report.experience
     *
     * @mbg.generated
     */
    private String experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_lab_report
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.id
     *
     * @return the value of hz_lab_report.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.id
     *
     * @param id the value for hz_lab_report.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.course_id
     *
     * @return the value of hz_lab_report.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.course_id
     *
     * @param courseId the value for hz_lab_report.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.test_id
     *
     * @return the value of hz_lab_report.test_id
     *
     * @mbg.generated
     */
    public String getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.test_id
     *
     * @param testId the value for hz_lab_report.test_id
     *
     * @mbg.generated
     */
    public void setTestId(String testId) {
        this.testId = testId == null ? null : testId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.test_target
     *
     * @return the value of hz_lab_report.test_target
     *
     * @mbg.generated
     */
    public String getTestTarget() {
        return testTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.test_target
     *
     * @param testTarget the value for hz_lab_report.test_target
     *
     * @mbg.generated
     */
    public void setTestTarget(String testTarget) {
        this.testTarget = testTarget == null ? null : testTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.test_request
     *
     * @return the value of hz_lab_report.test_request
     *
     * @mbg.generated
     */
    public String getTestRequest() {
        return testRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.test_request
     *
     * @param testRequest the value for hz_lab_report.test_request
     *
     * @mbg.generated
     */
    public void setTestRequest(String testRequest) {
        this.testRequest = testRequest == null ? null : testRequest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.test_environment
     *
     * @return the value of hz_lab_report.test_environment
     *
     * @mbg.generated
     */
    public String getTestEnvironment() {
        return testEnvironment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.test_environment
     *
     * @param testEnvironment the value for hz_lab_report.test_environment
     *
     * @mbg.generated
     */
    public void setTestEnvironment(String testEnvironment) {
        this.testEnvironment = testEnvironment == null ? null : testEnvironment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.test_comment
     *
     * @return the value of hz_lab_report.test_comment
     *
     * @mbg.generated
     */
    public String getTestComment() {
        return testComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.test_comment
     *
     * @param testComment the value for hz_lab_report.test_comment
     *
     * @mbg.generated
     */
    public void setTestComment(String testComment) {
        this.testComment = testComment == null ? null : testComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.class_id
     *
     * @return the value of hz_lab_report.class_id
     *
     * @mbg.generated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.class_id
     *
     * @param classId the value for hz_lab_report.class_id
     *
     * @mbg.generated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.class_name
     *
     * @return the value of hz_lab_report.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.class_name
     *
     * @param className the value for hz_lab_report.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.read_state
     *
     * @return the value of hz_lab_report.read_state
     *
     * @mbg.generated
     */
    public Integer getReadState() {
        return readState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.read_state
     *
     * @param readState the value for hz_lab_report.read_state
     *
     * @mbg.generated
     */
    public void setReadState(Integer readState) {
        this.readState = readState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.read_time
     *
     * @return the value of hz_lab_report.read_time
     *
     * @mbg.generated
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.read_time
     *
     * @param readTime the value for hz_lab_report.read_time
     *
     * @mbg.generated
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.read_name
     *
     * @return the value of hz_lab_report.read_name
     *
     * @mbg.generated
     */
    public String getReadName() {
        return readName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.read_name
     *
     * @param readName the value for hz_lab_report.read_name
     *
     * @mbg.generated
     */
    public void setReadName(String readName) {
        this.readName = readName == null ? null : readName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.read_comment
     *
     * @return the value of hz_lab_report.read_comment
     *
     * @mbg.generated
     */
    public String getReadComment() {
        return readComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.read_comment
     *
     * @param readComment the value for hz_lab_report.read_comment
     *
     * @mbg.generated
     */
    public void setReadComment(String readComment) {
        this.readComment = readComment == null ? null : readComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.score
     *
     * @return the value of hz_lab_report.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.score
     *
     * @param score the value for hz_lab_report.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.level
     *
     * @return the value of hz_lab_report.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.level
     *
     * @param level the value for hz_lab_report.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.create_id
     *
     * @return the value of hz_lab_report.create_id
     *
     * @mbg.generated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.create_id
     *
     * @param createId the value for hz_lab_report.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.create_name
     *
     * @return the value of hz_lab_report.create_name
     *
     * @mbg.generated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.create_name
     *
     * @param createName the value for hz_lab_report.create_name
     *
     * @mbg.generated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.create_time
     *
     * @return the value of hz_lab_report.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.create_time
     *
     * @param createTime the value for hz_lab_report.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.difficult_level
     *
     * @return the value of hz_lab_report.difficult_level
     *
     * @mbg.generated
     */
    public Integer getDifficultLevel() {
        return difficultLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.difficult_level
     *
     * @param difficultLevel the value for hz_lab_report.difficult_level
     *
     * @mbg.generated
     */
    public void setDifficultLevel(Integer difficultLevel) {
        this.difficultLevel = difficultLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.advice
     *
     * @return the value of hz_lab_report.advice
     *
     * @mbg.generated
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.advice
     *
     * @param advice the value for hz_lab_report.advice
     *
     * @mbg.generated
     */
    public void setAdvice(String advice) {
        this.advice = advice == null ? null : advice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.back_reason
     *
     * @return the value of hz_lab_report.back_reason
     *
     * @mbg.generated
     */
    public String getBackReason() {
        return backReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.back_reason
     *
     * @param backReason the value for hz_lab_report.back_reason
     *
     * @mbg.generated
     */
    public void setBackReason(String backReason) {
        this.backReason = backReason == null ? null : backReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.score_state
     *
     * @return the value of hz_lab_report.score_state
     *
     * @mbg.generated
     */
    public Integer getScoreState() {
        return scoreState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.score_state
     *
     * @param scoreState the value for hz_lab_report.score_state
     *
     * @mbg.generated
     */
    public void setScoreState(Integer scoreState) {
        this.scoreState = scoreState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.test_result
     *
     * @return the value of hz_lab_report.test_result
     *
     * @mbg.generated
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.test_result
     *
     * @param testResult the value for hz_lab_report.test_result
     *
     * @mbg.generated
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult == null ? null : testResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.test_result_html
     *
     * @return the value of hz_lab_report.test_result_html
     *
     * @mbg.generated
     */
    public String getTestResultHtml() {
        return testResultHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.test_result_html
     *
     * @param testResultHtml the value for hz_lab_report.test_result_html
     *
     * @mbg.generated
     */
    public void setTestResultHtml(String testResultHtml) {
        this.testResultHtml = testResultHtml == null ? null : testResultHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lab_report.experience
     *
     * @return the value of hz_lab_report.experience
     *
     * @mbg.generated
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lab_report.experience
     *
     * @param experience the value for hz_lab_report.experience
     *
     * @mbg.generated
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_lab_report
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", courseId=").append(courseId);
        sb.append(", testId=").append(testId);
        sb.append(", testTarget=").append(testTarget);
        sb.append(", testRequest=").append(testRequest);
        sb.append(", testEnvironment=").append(testEnvironment);
        sb.append(", testComment=").append(testComment);
        sb.append(", classId=").append(classId);
        sb.append(", className=").append(className);
        sb.append(", readState=").append(readState);
        sb.append(", readTime=").append(readTime);
        sb.append(", readName=").append(readName);
        sb.append(", readComment=").append(readComment);
        sb.append(", score=").append(score);
        sb.append(", level=").append(level);
        sb.append(", createId=").append(createId);
        sb.append(", createName=").append(createName);
        sb.append(", createTime=").append(createTime);
        sb.append(", difficultLevel=").append(difficultLevel);
        sb.append(", advice=").append(advice);
        sb.append(", backReason=").append(backReason);
        sb.append(", scoreState=").append(scoreState);
        sb.append(", testResult=").append(testResult);
        sb.append(", testResultHtml=").append(testResultHtml);
        sb.append(", experience=").append(experience);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}