package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class HzLorePath implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lore_path.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lore_path.org_id
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lore_path.period_name
     *
     * @mbg.generated
     */
    private String periodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lore_path.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lore_path.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lore_path.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lore_path.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lore_path.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_lore_path.course_ids
     *
     * @mbg.generated
     */
    private String courseIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_lore_path
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lore_path.id
     *
     * @return the value of hz_lore_path.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lore_path.id
     *
     * @param id the value for hz_lore_path.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lore_path.org_id
     *
     * @return the value of hz_lore_path.org_id
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lore_path.org_id
     *
     * @param orgId the value for hz_lore_path.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lore_path.period_name
     *
     * @return the value of hz_lore_path.period_name
     *
     * @mbg.generated
     */
    public String getPeriodName() {
        return periodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lore_path.period_name
     *
     * @param periodName the value for hz_lore_path.period_name
     *
     * @mbg.generated
     */
    public void setPeriodName(String periodName) {
        this.periodName = periodName == null ? null : periodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lore_path.sort
     *
     * @return the value of hz_lore_path.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lore_path.sort
     *
     * @param sort the value for hz_lore_path.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lore_path.creator_id
     *
     * @return the value of hz_lore_path.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lore_path.creator_id
     *
     * @param creatorId the value for hz_lore_path.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lore_path.creator_name
     *
     * @return the value of hz_lore_path.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lore_path.creator_name
     *
     * @param creatorName the value for hz_lore_path.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lore_path.create_time
     *
     * @return the value of hz_lore_path.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lore_path.create_time
     *
     * @param createTime the value for hz_lore_path.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lore_path.is_delete
     *
     * @return the value of hz_lore_path.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lore_path.is_delete
     *
     * @param isDelete the value for hz_lore_path.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_lore_path.course_ids
     *
     * @return the value of hz_lore_path.course_ids
     *
     * @mbg.generated
     */
    public String getCourseIds() {
        return courseIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_lore_path.course_ids
     *
     * @param courseIds the value for hz_lore_path.course_ids
     *
     * @mbg.generated
     */
    public void setCourseIds(String courseIds) {
        this.courseIds = courseIds == null ? null : courseIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_lore_path
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orgId=").append(orgId);
        sb.append(", periodName=").append(periodName);
        sb.append(", sort=").append(sort);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", creatorName=").append(creatorName);
        sb.append(", createTime=").append(createTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", courseIds=").append(courseIds);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}