package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class HzQuestions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.answers_num
     *
     * @mbg.generated
     */
    private Integer answersNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.answer
     *
     * @mbg.generated
     */
    private Integer answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.test_id
     *
     * @mbg.generated
     */
    private String testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.times
     *
     * @mbg.generated
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.knowledge_id
     *
     * @mbg.generated
     */
    private String knowledgeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.question
     *
     * @mbg.generated
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.answers
     *
     * @mbg.generated
     */
    private String answers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_questions.analysis
     *
     * @mbg.generated
     */
    private String analysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_questions
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.id
     *
     * @return the value of hz_questions.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.id
     *
     * @param id the value for hz_questions.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.answers_num
     *
     * @return the value of hz_questions.answers_num
     *
     * @mbg.generated
     */
    public Integer getAnswersNum() {
        return answersNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.answers_num
     *
     * @param answersNum the value for hz_questions.answers_num
     *
     * @mbg.generated
     */
    public void setAnswersNum(Integer answersNum) {
        this.answersNum = answersNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.answer
     *
     * @return the value of hz_questions.answer
     *
     * @mbg.generated
     */
    public Integer getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.answer
     *
     * @param answer the value for hz_questions.answer
     *
     * @mbg.generated
     */
    public void setAnswer(Integer answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.type
     *
     * @return the value of hz_questions.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.type
     *
     * @param type the value for hz_questions.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.level
     *
     * @return the value of hz_questions.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.level
     *
     * @param level the value for hz_questions.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.state
     *
     * @return the value of hz_questions.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.state
     *
     * @param state the value for hz_questions.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.course_id
     *
     * @return the value of hz_questions.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.course_id
     *
     * @param courseId the value for hz_questions.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.test_id
     *
     * @return the value of hz_questions.test_id
     *
     * @mbg.generated
     */
    public String getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.test_id
     *
     * @param testId the value for hz_questions.test_id
     *
     * @mbg.generated
     */
    public void setTestId(String testId) {
        this.testId = testId == null ? null : testId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.create_user
     *
     * @return the value of hz_questions.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.create_user
     *
     * @param createUser the value for hz_questions.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.create_time
     *
     * @return the value of hz_questions.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.create_time
     *
     * @param createTime the value for hz_questions.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.times
     *
     * @return the value of hz_questions.times
     *
     * @mbg.generated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.times
     *
     * @param times the value for hz_questions.times
     *
     * @mbg.generated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.knowledge_id
     *
     * @return the value of hz_questions.knowledge_id
     *
     * @mbg.generated
     */
    public String getKnowledgeId() {
        return knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.knowledge_id
     *
     * @param knowledgeId the value for hz_questions.knowledge_id
     *
     * @mbg.generated
     */
    public void setKnowledgeId(String knowledgeId) {
        this.knowledgeId = knowledgeId == null ? null : knowledgeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.question
     *
     * @return the value of hz_questions.question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.question
     *
     * @param question the value for hz_questions.question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.answers
     *
     * @return the value of hz_questions.answers
     *
     * @mbg.generated
     */
    public String getAnswers() {
        return answers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.answers
     *
     * @param answers the value for hz_questions.answers
     *
     * @mbg.generated
     */
    public void setAnswers(String answers) {
        this.answers = answers == null ? null : answers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_questions.analysis
     *
     * @return the value of hz_questions.analysis
     *
     * @mbg.generated
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_questions.analysis
     *
     * @param analysis the value for hz_questions.analysis
     *
     * @mbg.generated
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_questions
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", answersNum=").append(answersNum);
        sb.append(", answer=").append(answer);
        sb.append(", type=").append(type);
        sb.append(", level=").append(level);
        sb.append(", state=").append(state);
        sb.append(", courseId=").append(courseId);
        sb.append(", testId=").append(testId);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", times=").append(times);
        sb.append(", knowledgeId=").append(knowledgeId);
        sb.append(", question=").append(question);
        sb.append(", answers=").append(answers);
        sb.append(", analysis=").append(analysis);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}