package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class HzTest implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.resource_id
     *
     * @mbg.generated
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.logo_url
     *
     * @mbg.generated
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.test_course_id
     *
     * @mbg.generated
     */
    private String testCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.test_name
     *
     * @mbg.generated
     */
    private String testName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.test_type
     *
     * @mbg.generated
     */
    private Integer testType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.lesson_count
     *
     * @mbg.generated
     */
    private Integer lessonCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.test_time
     *
     * @mbg.generated
     */
    private Integer testTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.test_summary
     *
     * @mbg.generated
     */
    private String testSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.test_target
     *
     * @mbg.generated
     */
    private String testTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.test_request
     *
     * @mbg.generated
     */
    private String testRequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.test_comment
     *
     * @mbg.generated
     */
    private String testComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.test_textbook
     *
     * @mbg.generated
     */
    private String testTextbook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.vm_count
     *
     * @mbg.generated
     */
    private Integer vmCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.last_update_time
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.updator_id
     *
     * @mbg.generated
     */
    private String updatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.updator_name
     *
     * @mbg.generated
     */
    private String updatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.vlan_group_id
     *
     * @mbg.generated
     */
    private String vlanGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.teacher_id
     *
     * @mbg.generated
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.is_basetest
     *
     * @mbg.generated
     */
    private Integer isBasetest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.basetest_id
     *
     * @mbg.generated
     */
    private String basetestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_test.percent_score
     *
     * @mbg.generated
     */
    private Integer percentScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_test
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.resource_id
     *
     * @return the value of hz_test.resource_id
     *
     * @mbg.generated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.resource_id
     *
     * @param resourceId the value for hz_test.resource_id
     *
     * @mbg.generated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.logo_url
     *
     * @return the value of hz_test.logo_url
     *
     * @mbg.generated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.logo_url
     *
     * @param logoUrl the value for hz_test.logo_url
     *
     * @mbg.generated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.test_course_id
     *
     * @return the value of hz_test.test_course_id
     *
     * @mbg.generated
     */
    public String getTestCourseId() {
        return testCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.test_course_id
     *
     * @param testCourseId the value for hz_test.test_course_id
     *
     * @mbg.generated
     */
    public void setTestCourseId(String testCourseId) {
        this.testCourseId = testCourseId == null ? null : testCourseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.test_name
     *
     * @return the value of hz_test.test_name
     *
     * @mbg.generated
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.test_name
     *
     * @param testName the value for hz_test.test_name
     *
     * @mbg.generated
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.test_type
     *
     * @return the value of hz_test.test_type
     *
     * @mbg.generated
     */
    public Integer getTestType() {
        return testType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.test_type
     *
     * @param testType the value for hz_test.test_type
     *
     * @mbg.generated
     */
    public void setTestType(Integer testType) {
        this.testType = testType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.lesson_count
     *
     * @return the value of hz_test.lesson_count
     *
     * @mbg.generated
     */
    public Integer getLessonCount() {
        return lessonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.lesson_count
     *
     * @param lessonCount the value for hz_test.lesson_count
     *
     * @mbg.generated
     */
    public void setLessonCount(Integer lessonCount) {
        this.lessonCount = lessonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.test_time
     *
     * @return the value of hz_test.test_time
     *
     * @mbg.generated
     */
    public Integer getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.test_time
     *
     * @param testTime the value for hz_test.test_time
     *
     * @mbg.generated
     */
    public void setTestTime(Integer testTime) {
        this.testTime = testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.test_summary
     *
     * @return the value of hz_test.test_summary
     *
     * @mbg.generated
     */
    public String getTestSummary() {
        return testSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.test_summary
     *
     * @param testSummary the value for hz_test.test_summary
     *
     * @mbg.generated
     */
    public void setTestSummary(String testSummary) {
        this.testSummary = testSummary == null ? null : testSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.test_target
     *
     * @return the value of hz_test.test_target
     *
     * @mbg.generated
     */
    public String getTestTarget() {
        return testTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.test_target
     *
     * @param testTarget the value for hz_test.test_target
     *
     * @mbg.generated
     */
    public void setTestTarget(String testTarget) {
        this.testTarget = testTarget == null ? null : testTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.test_request
     *
     * @return the value of hz_test.test_request
     *
     * @mbg.generated
     */
    public String getTestRequest() {
        return testRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.test_request
     *
     * @param testRequest the value for hz_test.test_request
     *
     * @mbg.generated
     */
    public void setTestRequest(String testRequest) {
        this.testRequest = testRequest == null ? null : testRequest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.test_comment
     *
     * @return the value of hz_test.test_comment
     *
     * @mbg.generated
     */
    public String getTestComment() {
        return testComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.test_comment
     *
     * @param testComment the value for hz_test.test_comment
     *
     * @mbg.generated
     */
    public void setTestComment(String testComment) {
        this.testComment = testComment == null ? null : testComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.sort
     *
     * @return the value of hz_test.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.sort
     *
     * @param sort the value for hz_test.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.test_textbook
     *
     * @return the value of hz_test.test_textbook
     *
     * @mbg.generated
     */
    public String getTestTextbook() {
        return testTextbook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.test_textbook
     *
     * @param testTextbook the value for hz_test.test_textbook
     *
     * @mbg.generated
     */
    public void setTestTextbook(String testTextbook) {
        this.testTextbook = testTextbook == null ? null : testTextbook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.remark
     *
     * @return the value of hz_test.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.remark
     *
     * @param remark the value for hz_test.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.vm_count
     *
     * @return the value of hz_test.vm_count
     *
     * @mbg.generated
     */
    public Integer getVmCount() {
        return vmCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.vm_count
     *
     * @param vmCount the value for hz_test.vm_count
     *
     * @mbg.generated
     */
    public void setVmCount(Integer vmCount) {
        this.vmCount = vmCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.create_time
     *
     * @return the value of hz_test.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.create_time
     *
     * @param createTime the value for hz_test.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.creator_id
     *
     * @return the value of hz_test.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.creator_id
     *
     * @param creatorId the value for hz_test.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.creator_name
     *
     * @return the value of hz_test.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.creator_name
     *
     * @param creatorName the value for hz_test.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.last_update_time
     *
     * @return the value of hz_test.last_update_time
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.last_update_time
     *
     * @param lastUpdateTime the value for hz_test.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.updator_id
     *
     * @return the value of hz_test.updator_id
     *
     * @mbg.generated
     */
    public String getUpdatorId() {
        return updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.updator_id
     *
     * @param updatorId the value for hz_test.updator_id
     *
     * @mbg.generated
     */
    public void setUpdatorId(String updatorId) {
        this.updatorId = updatorId == null ? null : updatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.updator_name
     *
     * @return the value of hz_test.updator_name
     *
     * @mbg.generated
     */
    public String getUpdatorName() {
        return updatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.updator_name
     *
     * @param updatorName the value for hz_test.updator_name
     *
     * @mbg.generated
     */
    public void setUpdatorName(String updatorName) {
        this.updatorName = updatorName == null ? null : updatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.is_delete
     *
     * @return the value of hz_test.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.is_delete
     *
     * @param isDelete the value for hz_test.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.vlan_group_id
     *
     * @return the value of hz_test.vlan_group_id
     *
     * @mbg.generated
     */
    public String getVlanGroupId() {
        return vlanGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.vlan_group_id
     *
     * @param vlanGroupId the value for hz_test.vlan_group_id
     *
     * @mbg.generated
     */
    public void setVlanGroupId(String vlanGroupId) {
        this.vlanGroupId = vlanGroupId == null ? null : vlanGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.teacher_id
     *
     * @return the value of hz_test.teacher_id
     *
     * @mbg.generated
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.teacher_id
     *
     * @param teacherId the value for hz_test.teacher_id
     *
     * @mbg.generated
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.is_basetest
     *
     * @return the value of hz_test.is_basetest
     *
     * @mbg.generated
     */
    public Integer getIsBasetest() {
        return isBasetest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.is_basetest
     *
     * @param isBasetest the value for hz_test.is_basetest
     *
     * @mbg.generated
     */
    public void setIsBasetest(Integer isBasetest) {
        this.isBasetest = isBasetest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.basetest_id
     *
     * @return the value of hz_test.basetest_id
     *
     * @mbg.generated
     */
    public String getBasetestId() {
        return basetestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.basetest_id
     *
     * @param basetestId the value for hz_test.basetest_id
     *
     * @mbg.generated
     */
    public void setBasetestId(String basetestId) {
        this.basetestId = basetestId == null ? null : basetestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_test.percent_score
     *
     * @return the value of hz_test.percent_score
     *
     * @mbg.generated
     */
    public Integer getPercentScore() {
        return percentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_test.percent_score
     *
     * @param percentScore the value for hz_test.percent_score
     *
     * @mbg.generated
     */
    public void setPercentScore(Integer percentScore) {
        this.percentScore = percentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_test
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resourceId=").append(resourceId);
        sb.append(", logoUrl=").append(logoUrl);
        sb.append(", testCourseId=").append(testCourseId);
        sb.append(", testName=").append(testName);
        sb.append(", testType=").append(testType);
        sb.append(", lessonCount=").append(lessonCount);
        sb.append(", testTime=").append(testTime);
        sb.append(", testSummary=").append(testSummary);
        sb.append(", testTarget=").append(testTarget);
        sb.append(", testRequest=").append(testRequest);
        sb.append(", testComment=").append(testComment);
        sb.append(", sort=").append(sort);
        sb.append(", testTextbook=").append(testTextbook);
        sb.append(", remark=").append(remark);
        sb.append(", vmCount=").append(vmCount);
        sb.append(", createTime=").append(createTime);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", creatorName=").append(creatorName);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", updatorId=").append(updatorId);
        sb.append(", updatorName=").append(updatorName);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", vlanGroupId=").append(vlanGroupId);
        sb.append(", teacherId=").append(teacherId);
        sb.append(", isBasetest=").append(isBasetest);
        sb.append(", basetestId=").append(basetestId);
        sb.append(", percentScore=").append(percentScore);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}