package com.example.springboot.pojo;

import java.io.Serializable;

public class HzVlanGroupScheme implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_vlan_group_scheme.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_vlan_group_scheme.vlan_group_id
     *
     * @mbg.generated
     */
    private String vlanGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_vlan_group_scheme.template_id
     *
     * @mbg.generated
     */
    private String templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_vlan_group_scheme.is_install
     *
     * @mbg.generated
     */
    private Integer isInstall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_vlan_group_scheme.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_vlan_group_scheme
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_vlan_group_scheme.id
     *
     * @return the value of hz_vlan_group_scheme.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_vlan_group_scheme.id
     *
     * @param id the value for hz_vlan_group_scheme.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_vlan_group_scheme.vlan_group_id
     *
     * @return the value of hz_vlan_group_scheme.vlan_group_id
     *
     * @mbg.generated
     */
    public String getVlanGroupId() {
        return vlanGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_vlan_group_scheme.vlan_group_id
     *
     * @param vlanGroupId the value for hz_vlan_group_scheme.vlan_group_id
     *
     * @mbg.generated
     */
    public void setVlanGroupId(String vlanGroupId) {
        this.vlanGroupId = vlanGroupId == null ? null : vlanGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_vlan_group_scheme.template_id
     *
     * @return the value of hz_vlan_group_scheme.template_id
     *
     * @mbg.generated
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_vlan_group_scheme.template_id
     *
     * @param templateId the value for hz_vlan_group_scheme.template_id
     *
     * @mbg.generated
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_vlan_group_scheme.is_install
     *
     * @return the value of hz_vlan_group_scheme.is_install
     *
     * @mbg.generated
     */
    public Integer getIsInstall() {
        return isInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_vlan_group_scheme.is_install
     *
     * @param isInstall the value for hz_vlan_group_scheme.is_install
     *
     * @mbg.generated
     */
    public void setIsInstall(Integer isInstall) {
        this.isInstall = isInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_vlan_group_scheme.pid
     *
     * @return the value of hz_vlan_group_scheme.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_vlan_group_scheme.pid
     *
     * @param pid the value for hz_vlan_group_scheme.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_vlan_group_scheme
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", vlanGroupId=").append(vlanGroupId);
        sb.append(", templateId=").append(templateId);
        sb.append(", isInstall=").append(isInstall);
        sb.append(", pid=").append(pid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}