package com.example.springboot.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Umdict implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umdict.DICTID
     *
     * @mbg.generated
     */
    private String dictid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umdict.DICTCODE
     *
     * @mbg.generated
     */
    private String dictcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umdict.DICTNAME
     *
     * @mbg.generated
     */
    private String dictname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umdict.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umdict.SHOWORDER
     *
     * @mbg.generated
     */
    private BigDecimal showorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umdict
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umdict.DICTID
     *
     * @return the value of umdict.DICTID
     *
     * @mbg.generated
     */
    public String getDictid() {
        return dictid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umdict.DICTID
     *
     * @param dictid the value for umdict.DICTID
     *
     * @mbg.generated
     */
    public void setDictid(String dictid) {
        this.dictid = dictid == null ? null : dictid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umdict.DICTCODE
     *
     * @return the value of umdict.DICTCODE
     *
     * @mbg.generated
     */
    public String getDictcode() {
        return dictcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umdict.DICTCODE
     *
     * @param dictcode the value for umdict.DICTCODE
     *
     * @mbg.generated
     */
    public void setDictcode(String dictcode) {
        this.dictcode = dictcode == null ? null : dictcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umdict.DICTNAME
     *
     * @return the value of umdict.DICTNAME
     *
     * @mbg.generated
     */
    public String getDictname() {
        return dictname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umdict.DICTNAME
     *
     * @param dictname the value for umdict.DICTNAME
     *
     * @mbg.generated
     */
    public void setDictname(String dictname) {
        this.dictname = dictname == null ? null : dictname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umdict.MEMO
     *
     * @return the value of umdict.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umdict.MEMO
     *
     * @param memo the value for umdict.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umdict.SHOWORDER
     *
     * @return the value of umdict.SHOWORDER
     *
     * @mbg.generated
     */
    public BigDecimal getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umdict.SHOWORDER
     *
     * @param showorder the value for umdict.SHOWORDER
     *
     * @mbg.generated
     */
    public void setShoworder(BigDecimal showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umdict
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dictid=").append(dictid);
        sb.append(", dictcode=").append(dictcode);
        sb.append(", dictname=").append(dictname);
        sb.append(", memo=").append(memo);
        sb.append(", showorder=").append(showorder);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}