package com.example.springboot.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Umgroupitem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umgroupitem.GROUPITEMID
     *
     * @mbg.generated
     */
    private String groupitemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umgroupitem.GROUPID
     *
     * @mbg.generated
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umgroupitem.ORGID
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umgroupitem.ORGNAME
     *
     * @mbg.generated
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umgroupitem.ORGTYPE
     *
     * @mbg.generated
     */
    private String orgtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umgroupitem.SHOWORDER
     *
     * @mbg.generated
     */
    private BigDecimal showorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umgroupitem
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umgroupitem.GROUPITEMID
     *
     * @return the value of umgroupitem.GROUPITEMID
     *
     * @mbg.generated
     */
    public String getGroupitemid() {
        return groupitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umgroupitem.GROUPITEMID
     *
     * @param groupitemid the value for umgroupitem.GROUPITEMID
     *
     * @mbg.generated
     */
    public void setGroupitemid(String groupitemid) {
        this.groupitemid = groupitemid == null ? null : groupitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umgroupitem.GROUPID
     *
     * @return the value of umgroupitem.GROUPID
     *
     * @mbg.generated
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umgroupitem.GROUPID
     *
     * @param groupid the value for umgroupitem.GROUPID
     *
     * @mbg.generated
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umgroupitem.ORGID
     *
     * @return the value of umgroupitem.ORGID
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umgroupitem.ORGID
     *
     * @param orgid the value for umgroupitem.ORGID
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umgroupitem.ORGNAME
     *
     * @return the value of umgroupitem.ORGNAME
     *
     * @mbg.generated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umgroupitem.ORGNAME
     *
     * @param orgname the value for umgroupitem.ORGNAME
     *
     * @mbg.generated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umgroupitem.ORGTYPE
     *
     * @return the value of umgroupitem.ORGTYPE
     *
     * @mbg.generated
     */
    public String getOrgtype() {
        return orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umgroupitem.ORGTYPE
     *
     * @param orgtype the value for umgroupitem.ORGTYPE
     *
     * @mbg.generated
     */
    public void setOrgtype(String orgtype) {
        this.orgtype = orgtype == null ? null : orgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umgroupitem.SHOWORDER
     *
     * @return the value of umgroupitem.SHOWORDER
     *
     * @mbg.generated
     */
    public BigDecimal getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umgroupitem.SHOWORDER
     *
     * @param showorder the value for umgroupitem.SHOWORDER
     *
     * @mbg.generated
     */
    public void setShoworder(BigDecimal showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umgroupitem
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupitemid=").append(groupitemid);
        sb.append(", groupid=").append(groupid);
        sb.append(", orgid=").append(orgid);
        sb.append(", orgname=").append(orgname);
        sb.append(", orgtype=").append(orgtype);
        sb.append(", showorder=").append(showorder);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}