package com.example.springboot.pojo;

import java.io.Serializable;

public class Ummenuitem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.MENUITEMID
     *
     * @mbg.generated
     */
    private String menuitemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.MENUID
     *
     * @mbg.generated
     */
    private String menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.CAPTION
     *
     * @mbg.generated
     */
    private String caption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.SHOWTYPE
     *
     * @mbg.generated
     */
    private String showtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.PAGETYPE
     *
     * @mbg.generated
     */
    private String pagetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.JSFUNCTION
     *
     * @mbg.generated
     */
    private String jsfunction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.OBJECTID
     *
     * @mbg.generated
     */
    private String objectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.ICONFILE
     *
     * @mbg.generated
     */
    private String iconfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.SHOWORDER
     *
     * @mbg.generated
     */
    private Long showorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.PARAMAP
     *
     * @mbg.generated
     */
    private String paramap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.TARGET
     *
     * @mbg.generated
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.REFMENUID
     *
     * @mbg.generated
     */
    private String refmenuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenuitem.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ummenuitem
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.MENUITEMID
     *
     * @return the value of ummenuitem.MENUITEMID
     *
     * @mbg.generated
     */
    public String getMenuitemid() {
        return menuitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.MENUITEMID
     *
     * @param menuitemid the value for ummenuitem.MENUITEMID
     *
     * @mbg.generated
     */
    public void setMenuitemid(String menuitemid) {
        this.menuitemid = menuitemid == null ? null : menuitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.MENUID
     *
     * @return the value of ummenuitem.MENUID
     *
     * @mbg.generated
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.MENUID
     *
     * @param menuid the value for ummenuitem.MENUID
     *
     * @mbg.generated
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.CAPTION
     *
     * @return the value of ummenuitem.CAPTION
     *
     * @mbg.generated
     */
    public String getCaption() {
        return caption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.CAPTION
     *
     * @param caption the value for ummenuitem.CAPTION
     *
     * @mbg.generated
     */
    public void setCaption(String caption) {
        this.caption = caption == null ? null : caption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.SHOWTYPE
     *
     * @return the value of ummenuitem.SHOWTYPE
     *
     * @mbg.generated
     */
    public String getShowtype() {
        return showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.SHOWTYPE
     *
     * @param showtype the value for ummenuitem.SHOWTYPE
     *
     * @mbg.generated
     */
    public void setShowtype(String showtype) {
        this.showtype = showtype == null ? null : showtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.PAGETYPE
     *
     * @return the value of ummenuitem.PAGETYPE
     *
     * @mbg.generated
     */
    public String getPagetype() {
        return pagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.PAGETYPE
     *
     * @param pagetype the value for ummenuitem.PAGETYPE
     *
     * @mbg.generated
     */
    public void setPagetype(String pagetype) {
        this.pagetype = pagetype == null ? null : pagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.JSFUNCTION
     *
     * @return the value of ummenuitem.JSFUNCTION
     *
     * @mbg.generated
     */
    public String getJsfunction() {
        return jsfunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.JSFUNCTION
     *
     * @param jsfunction the value for ummenuitem.JSFUNCTION
     *
     * @mbg.generated
     */
    public void setJsfunction(String jsfunction) {
        this.jsfunction = jsfunction == null ? null : jsfunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.OBJECTID
     *
     * @return the value of ummenuitem.OBJECTID
     *
     * @mbg.generated
     */
    public String getObjectid() {
        return objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.OBJECTID
     *
     * @param objectid the value for ummenuitem.OBJECTID
     *
     * @mbg.generated
     */
    public void setObjectid(String objectid) {
        this.objectid = objectid == null ? null : objectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.ICONFILE
     *
     * @return the value of ummenuitem.ICONFILE
     *
     * @mbg.generated
     */
    public String getIconfile() {
        return iconfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.ICONFILE
     *
     * @param iconfile the value for ummenuitem.ICONFILE
     *
     * @mbg.generated
     */
    public void setIconfile(String iconfile) {
        this.iconfile = iconfile == null ? null : iconfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.SHOWORDER
     *
     * @return the value of ummenuitem.SHOWORDER
     *
     * @mbg.generated
     */
    public Long getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.SHOWORDER
     *
     * @param showorder the value for ummenuitem.SHOWORDER
     *
     * @mbg.generated
     */
    public void setShoworder(Long showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.PARAMAP
     *
     * @return the value of ummenuitem.PARAMAP
     *
     * @mbg.generated
     */
    public String getParamap() {
        return paramap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.PARAMAP
     *
     * @param paramap the value for ummenuitem.PARAMAP
     *
     * @mbg.generated
     */
    public void setParamap(String paramap) {
        this.paramap = paramap == null ? null : paramap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.TARGET
     *
     * @return the value of ummenuitem.TARGET
     *
     * @mbg.generated
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.TARGET
     *
     * @param target the value for ummenuitem.TARGET
     *
     * @mbg.generated
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.REFMENUID
     *
     * @return the value of ummenuitem.REFMENUID
     *
     * @mbg.generated
     */
    public String getRefmenuid() {
        return refmenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.REFMENUID
     *
     * @param refmenuid the value for ummenuitem.REFMENUID
     *
     * @mbg.generated
     */
    public void setRefmenuid(String refmenuid) {
        this.refmenuid = refmenuid == null ? null : refmenuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenuitem.MEMO
     *
     * @return the value of ummenuitem.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenuitem.MEMO
     *
     * @param memo the value for ummenuitem.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ummenuitem
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuitemid=").append(menuitemid);
        sb.append(", menuid=").append(menuid);
        sb.append(", caption=").append(caption);
        sb.append(", showtype=").append(showtype);
        sb.append(", pagetype=").append(pagetype);
        sb.append(", jsfunction=").append(jsfunction);
        sb.append(", objectid=").append(objectid);
        sb.append(", iconfile=").append(iconfile);
        sb.append(", showorder=").append(showorder);
        sb.append(", paramap=").append(paramap);
        sb.append(", target=").append(target);
        sb.append(", refmenuid=").append(refmenuid);
        sb.append(", memo=").append(memo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}