package com.example.springboot.pojo;

import java.io.Serializable;

public class Ummenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.MENUID
     *
     * @mbg.generated
     */
    private String menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.MENUCODE
     *
     * @mbg.generated
     */
    private String menucode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.SYSCODE
     *
     * @mbg.generated
     */
    private String syscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.MENUNAME
     *
     * @mbg.generated
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.SHOWTYPE
     *
     * @mbg.generated
     */
    private String showtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.REFURL
     *
     * @mbg.generated
     */
    private String refurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.PARENTID
     *
     * @mbg.generated
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.SMALLICON
     *
     * @mbg.generated
     */
    private String smallicon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.BIGICON
     *
     * @mbg.generated
     */
    private String bigicon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.APPTYPE
     *
     * @mbg.generated
     */
    private String apptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.SHOWORDER
     *
     * @mbg.generated
     */
    private Long showorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.PARENTIDS
     *
     * @mbg.generated
     */
    private String parentids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.LEAF
     *
     * @mbg.generated
     */
    private String leaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.TARGET
     *
     * @mbg.generated
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.REFSYS
     *
     * @mbg.generated
     */
    private String refsys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.PROCESSID
     *
     * @mbg.generated
     */
    private String processid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ummenu.MENUTYPE
     *
     * @mbg.generated
     */
    private String menutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ummenu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.MENUID
     *
     * @return the value of ummenu.MENUID
     *
     * @mbg.generated
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.MENUID
     *
     * @param menuid the value for ummenu.MENUID
     *
     * @mbg.generated
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.MENUCODE
     *
     * @return the value of ummenu.MENUCODE
     *
     * @mbg.generated
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.MENUCODE
     *
     * @param menucode the value for ummenu.MENUCODE
     *
     * @mbg.generated
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.SYSCODE
     *
     * @return the value of ummenu.SYSCODE
     *
     * @mbg.generated
     */
    public String getSyscode() {
        return syscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.SYSCODE
     *
     * @param syscode the value for ummenu.SYSCODE
     *
     * @mbg.generated
     */
    public void setSyscode(String syscode) {
        this.syscode = syscode == null ? null : syscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.MENUNAME
     *
     * @return the value of ummenu.MENUNAME
     *
     * @mbg.generated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.MENUNAME
     *
     * @param menuname the value for ummenu.MENUNAME
     *
     * @mbg.generated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.SHOWTYPE
     *
     * @return the value of ummenu.SHOWTYPE
     *
     * @mbg.generated
     */
    public String getShowtype() {
        return showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.SHOWTYPE
     *
     * @param showtype the value for ummenu.SHOWTYPE
     *
     * @mbg.generated
     */
    public void setShowtype(String showtype) {
        this.showtype = showtype == null ? null : showtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.REFURL
     *
     * @return the value of ummenu.REFURL
     *
     * @mbg.generated
     */
    public String getRefurl() {
        return refurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.REFURL
     *
     * @param refurl the value for ummenu.REFURL
     *
     * @mbg.generated
     */
    public void setRefurl(String refurl) {
        this.refurl = refurl == null ? null : refurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.PARENTID
     *
     * @return the value of ummenu.PARENTID
     *
     * @mbg.generated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.PARENTID
     *
     * @param parentid the value for ummenu.PARENTID
     *
     * @mbg.generated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.SMALLICON
     *
     * @return the value of ummenu.SMALLICON
     *
     * @mbg.generated
     */
    public String getSmallicon() {
        return smallicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.SMALLICON
     *
     * @param smallicon the value for ummenu.SMALLICON
     *
     * @mbg.generated
     */
    public void setSmallicon(String smallicon) {
        this.smallicon = smallicon == null ? null : smallicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.BIGICON
     *
     * @return the value of ummenu.BIGICON
     *
     * @mbg.generated
     */
    public String getBigicon() {
        return bigicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.BIGICON
     *
     * @param bigicon the value for ummenu.BIGICON
     *
     * @mbg.generated
     */
    public void setBigicon(String bigicon) {
        this.bigicon = bigicon == null ? null : bigicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.APPTYPE
     *
     * @return the value of ummenu.APPTYPE
     *
     * @mbg.generated
     */
    public String getApptype() {
        return apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.APPTYPE
     *
     * @param apptype the value for ummenu.APPTYPE
     *
     * @mbg.generated
     */
    public void setApptype(String apptype) {
        this.apptype = apptype == null ? null : apptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.SHOWORDER
     *
     * @return the value of ummenu.SHOWORDER
     *
     * @mbg.generated
     */
    public Long getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.SHOWORDER
     *
     * @param showorder the value for ummenu.SHOWORDER
     *
     * @mbg.generated
     */
    public void setShoworder(Long showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.PARENTIDS
     *
     * @return the value of ummenu.PARENTIDS
     *
     * @mbg.generated
     */
    public String getParentids() {
        return parentids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.PARENTIDS
     *
     * @param parentids the value for ummenu.PARENTIDS
     *
     * @mbg.generated
     */
    public void setParentids(String parentids) {
        this.parentids = parentids == null ? null : parentids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.LEAF
     *
     * @return the value of ummenu.LEAF
     *
     * @mbg.generated
     */
    public String getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.LEAF
     *
     * @param leaf the value for ummenu.LEAF
     *
     * @mbg.generated
     */
    public void setLeaf(String leaf) {
        this.leaf = leaf == null ? null : leaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.TARGET
     *
     * @return the value of ummenu.TARGET
     *
     * @mbg.generated
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.TARGET
     *
     * @param target the value for ummenu.TARGET
     *
     * @mbg.generated
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.REFSYS
     *
     * @return the value of ummenu.REFSYS
     *
     * @mbg.generated
     */
    public String getRefsys() {
        return refsys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.REFSYS
     *
     * @param refsys the value for ummenu.REFSYS
     *
     * @mbg.generated
     */
    public void setRefsys(String refsys) {
        this.refsys = refsys == null ? null : refsys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.PROCESSID
     *
     * @return the value of ummenu.PROCESSID
     *
     * @mbg.generated
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.PROCESSID
     *
     * @param processid the value for ummenu.PROCESSID
     *
     * @mbg.generated
     */
    public void setProcessid(String processid) {
        this.processid = processid == null ? null : processid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ummenu.MENUTYPE
     *
     * @return the value of ummenu.MENUTYPE
     *
     * @mbg.generated
     */
    public String getMenutype() {
        return menutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ummenu.MENUTYPE
     *
     * @param menutype the value for ummenu.MENUTYPE
     *
     * @mbg.generated
     */
    public void setMenutype(String menutype) {
        this.menutype = menutype == null ? null : menutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ummenu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuid=").append(menuid);
        sb.append(", menucode=").append(menucode);
        sb.append(", syscode=").append(syscode);
        sb.append(", menuname=").append(menuname);
        sb.append(", showtype=").append(showtype);
        sb.append(", refurl=").append(refurl);
        sb.append(", parentid=").append(parentid);
        sb.append(", smallicon=").append(smallicon);
        sb.append(", bigicon=").append(bigicon);
        sb.append(", apptype=").append(apptype);
        sb.append(", showorder=").append(showorder);
        sb.append(", parentids=").append(parentids);
        sb.append(", leaf=").append(leaf);
        sb.append(", target=").append(target);
        sb.append(", refsys=").append(refsys);
        sb.append(", processid=").append(processid);
        sb.append(", menutype=").append(menutype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}