package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class Umorg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.ORGID
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.ORGNAME
     *
     * @mbg.generated
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.SHORTNAME
     *
     * @mbg.generated
     */
    private String shortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.PARENTID
     *
     * @mbg.generated
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.ORGTYPE
     *
     * @mbg.generated
     */
    private String orgtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.SAPID
     *
     * @mbg.generated
     */
    private String sapid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.SHOWORDER
     *
     * @mbg.generated
     */
    private Long showorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.CREATEDATE
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.PARENTIDS
     *
     * @mbg.generated
     */
    private String parentids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.PARENTNAMES
     *
     * @mbg.generated
     */
    private String parentnames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.LEAF
     *
     * @mbg.generated
     */
    private String leaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.LEADER
     *
     * @mbg.generated
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.PRINCIPAL
     *
     * @mbg.generated
     */
    private String principal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.ORGATTRIBUTE
     *
     * @mbg.generated
     */
    private String orgattribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.ORGCODE
     *
     * @mbg.generated
     */
    private String orgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.PARENTTYPES
     *
     * @mbg.generated
     */
    private String parenttypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.REFORGID
     *
     * @mbg.generated
     */
    private String reforgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.UM_ORGID
     *
     * @mbg.generated
     */
    private String umOrgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.UM_MAIL_ORGID
     *
     * @mbg.generated
     */
    private String umMailOrgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.class_type
     *
     * @mbg.generated
     */
    private Integer classType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umorg.grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umorg
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.ORGID
     *
     * @return the value of umorg.ORGID
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.ORGID
     *
     * @param orgid the value for umorg.ORGID
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.ORGNAME
     *
     * @return the value of umorg.ORGNAME
     *
     * @mbg.generated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.ORGNAME
     *
     * @param orgname the value for umorg.ORGNAME
     *
     * @mbg.generated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.SHORTNAME
     *
     * @return the value of umorg.SHORTNAME
     *
     * @mbg.generated
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.SHORTNAME
     *
     * @param shortname the value for umorg.SHORTNAME
     *
     * @mbg.generated
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.PARENTID
     *
     * @return the value of umorg.PARENTID
     *
     * @mbg.generated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.PARENTID
     *
     * @param parentid the value for umorg.PARENTID
     *
     * @mbg.generated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.MEMO
     *
     * @return the value of umorg.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.MEMO
     *
     * @param memo the value for umorg.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.ORGTYPE
     *
     * @return the value of umorg.ORGTYPE
     *
     * @mbg.generated
     */
    public String getOrgtype() {
        return orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.ORGTYPE
     *
     * @param orgtype the value for umorg.ORGTYPE
     *
     * @mbg.generated
     */
    public void setOrgtype(String orgtype) {
        this.orgtype = orgtype == null ? null : orgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.SAPID
     *
     * @return the value of umorg.SAPID
     *
     * @mbg.generated
     */
    public String getSapid() {
        return sapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.SAPID
     *
     * @param sapid the value for umorg.SAPID
     *
     * @mbg.generated
     */
    public void setSapid(String sapid) {
        this.sapid = sapid == null ? null : sapid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.SHOWORDER
     *
     * @return the value of umorg.SHOWORDER
     *
     * @mbg.generated
     */
    public Long getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.SHOWORDER
     *
     * @param showorder the value for umorg.SHOWORDER
     *
     * @mbg.generated
     */
    public void setShoworder(Long showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.CREATEDATE
     *
     * @return the value of umorg.CREATEDATE
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.CREATEDATE
     *
     * @param createdate the value for umorg.CREATEDATE
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.PARENTIDS
     *
     * @return the value of umorg.PARENTIDS
     *
     * @mbg.generated
     */
    public String getParentids() {
        return parentids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.PARENTIDS
     *
     * @param parentids the value for umorg.PARENTIDS
     *
     * @mbg.generated
     */
    public void setParentids(String parentids) {
        this.parentids = parentids == null ? null : parentids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.PARENTNAMES
     *
     * @return the value of umorg.PARENTNAMES
     *
     * @mbg.generated
     */
    public String getParentnames() {
        return parentnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.PARENTNAMES
     *
     * @param parentnames the value for umorg.PARENTNAMES
     *
     * @mbg.generated
     */
    public void setParentnames(String parentnames) {
        this.parentnames = parentnames == null ? null : parentnames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.LEAF
     *
     * @return the value of umorg.LEAF
     *
     * @mbg.generated
     */
    public String getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.LEAF
     *
     * @param leaf the value for umorg.LEAF
     *
     * @mbg.generated
     */
    public void setLeaf(String leaf) {
        this.leaf = leaf == null ? null : leaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.LEADER
     *
     * @return the value of umorg.LEADER
     *
     * @mbg.generated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.LEADER
     *
     * @param leader the value for umorg.LEADER
     *
     * @mbg.generated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.PRINCIPAL
     *
     * @return the value of umorg.PRINCIPAL
     *
     * @mbg.generated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.PRINCIPAL
     *
     * @param principal the value for umorg.PRINCIPAL
     *
     * @mbg.generated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.ORGATTRIBUTE
     *
     * @return the value of umorg.ORGATTRIBUTE
     *
     * @mbg.generated
     */
    public String getOrgattribute() {
        return orgattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.ORGATTRIBUTE
     *
     * @param orgattribute the value for umorg.ORGATTRIBUTE
     *
     * @mbg.generated
     */
    public void setOrgattribute(String orgattribute) {
        this.orgattribute = orgattribute == null ? null : orgattribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.ORGCODE
     *
     * @return the value of umorg.ORGCODE
     *
     * @mbg.generated
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.ORGCODE
     *
     * @param orgcode the value for umorg.ORGCODE
     *
     * @mbg.generated
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.PARENTTYPES
     *
     * @return the value of umorg.PARENTTYPES
     *
     * @mbg.generated
     */
    public String getParenttypes() {
        return parenttypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.PARENTTYPES
     *
     * @param parenttypes the value for umorg.PARENTTYPES
     *
     * @mbg.generated
     */
    public void setParenttypes(String parenttypes) {
        this.parenttypes = parenttypes == null ? null : parenttypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.REFORGID
     *
     * @return the value of umorg.REFORGID
     *
     * @mbg.generated
     */
    public String getReforgid() {
        return reforgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.REFORGID
     *
     * @param reforgid the value for umorg.REFORGID
     *
     * @mbg.generated
     */
    public void setReforgid(String reforgid) {
        this.reforgid = reforgid == null ? null : reforgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.UM_ORGID
     *
     * @return the value of umorg.UM_ORGID
     *
     * @mbg.generated
     */
    public String getUmOrgid() {
        return umOrgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.UM_ORGID
     *
     * @param umOrgid the value for umorg.UM_ORGID
     *
     * @mbg.generated
     */
    public void setUmOrgid(String umOrgid) {
        this.umOrgid = umOrgid == null ? null : umOrgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.UM_MAIL_ORGID
     *
     * @return the value of umorg.UM_MAIL_ORGID
     *
     * @mbg.generated
     */
    public String getUmMailOrgid() {
        return umMailOrgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.UM_MAIL_ORGID
     *
     * @param umMailOrgid the value for umorg.UM_MAIL_ORGID
     *
     * @mbg.generated
     */
    public void setUmMailOrgid(String umMailOrgid) {
        this.umMailOrgid = umMailOrgid == null ? null : umMailOrgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.del_flag
     *
     * @return the value of umorg.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.del_flag
     *
     * @param delFlag the value for umorg.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.logo
     *
     * @return the value of umorg.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.logo
     *
     * @param logo the value for umorg.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.class_type
     *
     * @return the value of umorg.class_type
     *
     * @mbg.generated
     */
    public Integer getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.class_type
     *
     * @param classType the value for umorg.class_type
     *
     * @mbg.generated
     */
    public void setClassType(Integer classType) {
        this.classType = classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umorg.grade
     *
     * @return the value of umorg.grade
     *
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umorg.grade
     *
     * @param grade the value for umorg.grade
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umorg
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orgid=").append(orgid);
        sb.append(", orgname=").append(orgname);
        sb.append(", shortname=").append(shortname);
        sb.append(", parentid=").append(parentid);
        sb.append(", memo=").append(memo);
        sb.append(", orgtype=").append(orgtype);
        sb.append(", sapid=").append(sapid);
        sb.append(", showorder=").append(showorder);
        sb.append(", createdate=").append(createdate);
        sb.append(", parentids=").append(parentids);
        sb.append(", parentnames=").append(parentnames);
        sb.append(", leaf=").append(leaf);
        sb.append(", leader=").append(leader);
        sb.append(", principal=").append(principal);
        sb.append(", orgattribute=").append(orgattribute);
        sb.append(", orgcode=").append(orgcode);
        sb.append(", parenttypes=").append(parenttypes);
        sb.append(", reforgid=").append(reforgid);
        sb.append(", umOrgid=").append(umOrgid);
        sb.append(", umMailOrgid=").append(umMailOrgid);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", logo=").append(logo);
        sb.append(", classType=").append(classType);
        sb.append(", grade=").append(grade);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}