package com.example.springboot.pojo;

import java.io.Serializable;

public class Umroleright implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umroleright.ROLERIGHTID
     *
     * @mbg.generated
     */
    private String rolerightid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umroleright.SYSCODE
     *
     * @mbg.generated
     */
    private String syscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umroleright.ROLEID
     *
     * @mbg.generated
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umroleright.MENUID
     *
     * @mbg.generated
     */
    private String menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umroleright.MENUITEMID
     *
     * @mbg.generated
     */
    private String menuitemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umroleright.ADMINS
     *
     * @mbg.generated
     */
    private String admins;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umroleright.OPERATE
     *
     * @mbg.generated
     */
    private String operate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umroleright
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umroleright.ROLERIGHTID
     *
     * @return the value of umroleright.ROLERIGHTID
     *
     * @mbg.generated
     */
    public String getRolerightid() {
        return rolerightid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umroleright.ROLERIGHTID
     *
     * @param rolerightid the value for umroleright.ROLERIGHTID
     *
     * @mbg.generated
     */
    public void setRolerightid(String rolerightid) {
        this.rolerightid = rolerightid == null ? null : rolerightid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umroleright.SYSCODE
     *
     * @return the value of umroleright.SYSCODE
     *
     * @mbg.generated
     */
    public String getSyscode() {
        return syscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umroleright.SYSCODE
     *
     * @param syscode the value for umroleright.SYSCODE
     *
     * @mbg.generated
     */
    public void setSyscode(String syscode) {
        this.syscode = syscode == null ? null : syscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umroleright.ROLEID
     *
     * @return the value of umroleright.ROLEID
     *
     * @mbg.generated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umroleright.ROLEID
     *
     * @param roleid the value for umroleright.ROLEID
     *
     * @mbg.generated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umroleright.MENUID
     *
     * @return the value of umroleright.MENUID
     *
     * @mbg.generated
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umroleright.MENUID
     *
     * @param menuid the value for umroleright.MENUID
     *
     * @mbg.generated
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umroleright.MENUITEMID
     *
     * @return the value of umroleright.MENUITEMID
     *
     * @mbg.generated
     */
    public String getMenuitemid() {
        return menuitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umroleright.MENUITEMID
     *
     * @param menuitemid the value for umroleright.MENUITEMID
     *
     * @mbg.generated
     */
    public void setMenuitemid(String menuitemid) {
        this.menuitemid = menuitemid == null ? null : menuitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umroleright.ADMINS
     *
     * @return the value of umroleright.ADMINS
     *
     * @mbg.generated
     */
    public String getAdmins() {
        return admins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umroleright.ADMINS
     *
     * @param admins the value for umroleright.ADMINS
     *
     * @mbg.generated
     */
    public void setAdmins(String admins) {
        this.admins = admins == null ? null : admins.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umroleright.OPERATE
     *
     * @return the value of umroleright.OPERATE
     *
     * @mbg.generated
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umroleright.OPERATE
     *
     * @param operate the value for umroleright.OPERATE
     *
     * @mbg.generated
     */
    public void setOperate(String operate) {
        this.operate = operate == null ? null : operate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umroleright
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rolerightid=").append(rolerightid);
        sb.append(", syscode=").append(syscode);
        sb.append(", roleid=").append(roleid);
        sb.append(", menuid=").append(menuid);
        sb.append(", menuitemid=").append(menuitemid);
        sb.append(", admins=").append(admins);
        sb.append(", operate=").append(operate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}