package com.example.springboot.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Umsystem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.SYSTEMID
     *
     * @mbg.generated
     */
    private String systemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.SYSCODE
     *
     * @mbg.generated
     */
    private String syscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.SYSNAME
     *
     * @mbg.generated
     */
    private String sysname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.CONTEXTS
     *
     * @mbg.generated
     */
    private String contexts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.SSOPAGE
     *
     * @mbg.generated
     */
    private String ssopage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.SHOWORDER
     *
     * @mbg.generated
     */
    private BigDecimal showorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.COSYS
     *
     * @mbg.generated
     */
    private String cosys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.EXTPROP
     *
     * @mbg.generated
     */
    private String extprop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.FRAMESETCODE
     *
     * @mbg.generated
     */
    private String framesetcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.SERVICEADDR
     *
     * @mbg.generated
     */
    private String serviceaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.HOST
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umsystem.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umsystem
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.SYSTEMID
     *
     * @return the value of umsystem.SYSTEMID
     *
     * @mbg.generated
     */
    public String getSystemid() {
        return systemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.SYSTEMID
     *
     * @param systemid the value for umsystem.SYSTEMID
     *
     * @mbg.generated
     */
    public void setSystemid(String systemid) {
        this.systemid = systemid == null ? null : systemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.SYSCODE
     *
     * @return the value of umsystem.SYSCODE
     *
     * @mbg.generated
     */
    public String getSyscode() {
        return syscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.SYSCODE
     *
     * @param syscode the value for umsystem.SYSCODE
     *
     * @mbg.generated
     */
    public void setSyscode(String syscode) {
        this.syscode = syscode == null ? null : syscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.SYSNAME
     *
     * @return the value of umsystem.SYSNAME
     *
     * @mbg.generated
     */
    public String getSysname() {
        return sysname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.SYSNAME
     *
     * @param sysname the value for umsystem.SYSNAME
     *
     * @mbg.generated
     */
    public void setSysname(String sysname) {
        this.sysname = sysname == null ? null : sysname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.CONTEXTS
     *
     * @return the value of umsystem.CONTEXTS
     *
     * @mbg.generated
     */
    public String getContexts() {
        return contexts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.CONTEXTS
     *
     * @param contexts the value for umsystem.CONTEXTS
     *
     * @mbg.generated
     */
    public void setContexts(String contexts) {
        this.contexts = contexts == null ? null : contexts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.SSOPAGE
     *
     * @return the value of umsystem.SSOPAGE
     *
     * @mbg.generated
     */
    public String getSsopage() {
        return ssopage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.SSOPAGE
     *
     * @param ssopage the value for umsystem.SSOPAGE
     *
     * @mbg.generated
     */
    public void setSsopage(String ssopage) {
        this.ssopage = ssopage == null ? null : ssopage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.MEMO
     *
     * @return the value of umsystem.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.MEMO
     *
     * @param memo the value for umsystem.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.STATUS
     *
     * @return the value of umsystem.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.STATUS
     *
     * @param status the value for umsystem.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.SHOWORDER
     *
     * @return the value of umsystem.SHOWORDER
     *
     * @mbg.generated
     */
    public BigDecimal getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.SHOWORDER
     *
     * @param showorder the value for umsystem.SHOWORDER
     *
     * @mbg.generated
     */
    public void setShoworder(BigDecimal showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.COSYS
     *
     * @return the value of umsystem.COSYS
     *
     * @mbg.generated
     */
    public String getCosys() {
        return cosys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.COSYS
     *
     * @param cosys the value for umsystem.COSYS
     *
     * @mbg.generated
     */
    public void setCosys(String cosys) {
        this.cosys = cosys == null ? null : cosys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.EXTPROP
     *
     * @return the value of umsystem.EXTPROP
     *
     * @mbg.generated
     */
    public String getExtprop() {
        return extprop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.EXTPROP
     *
     * @param extprop the value for umsystem.EXTPROP
     *
     * @mbg.generated
     */
    public void setExtprop(String extprop) {
        this.extprop = extprop == null ? null : extprop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.FRAMESETCODE
     *
     * @return the value of umsystem.FRAMESETCODE
     *
     * @mbg.generated
     */
    public String getFramesetcode() {
        return framesetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.FRAMESETCODE
     *
     * @param framesetcode the value for umsystem.FRAMESETCODE
     *
     * @mbg.generated
     */
    public void setFramesetcode(String framesetcode) {
        this.framesetcode = framesetcode == null ? null : framesetcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.SERVICEADDR
     *
     * @return the value of umsystem.SERVICEADDR
     *
     * @mbg.generated
     */
    public String getServiceaddr() {
        return serviceaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.SERVICEADDR
     *
     * @param serviceaddr the value for umsystem.SERVICEADDR
     *
     * @mbg.generated
     */
    public void setServiceaddr(String serviceaddr) {
        this.serviceaddr = serviceaddr == null ? null : serviceaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.HOST
     *
     * @return the value of umsystem.HOST
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.HOST
     *
     * @param host the value for umsystem.HOST
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsystem.del_flag
     *
     * @return the value of umsystem.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsystem.del_flag
     *
     * @param delFlag the value for umsystem.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsystem
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", systemid=").append(systemid);
        sb.append(", syscode=").append(syscode);
        sb.append(", sysname=").append(sysname);
        sb.append(", contexts=").append(contexts);
        sb.append(", ssopage=").append(ssopage);
        sb.append(", memo=").append(memo);
        sb.append(", status=").append(status);
        sb.append(", showorder=").append(showorder);
        sb.append(", cosys=").append(cosys);
        sb.append(", extprop=").append(extprop);
        sb.append(", framesetcode=").append(framesetcode);
        sb.append(", serviceaddr=").append(serviceaddr);
        sb.append(", host=").append(host);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}