package com.example.springboot.pojo;

import java.io.Serializable;
import java.util.Date;

public class Umuseroperlog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.resourceid
     *
     * @mbg.generated
     */
    private String resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.oper_type
     *
     * @mbg.generated
     */
    private String operType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.remote_addr
     *
     * @mbg.generated
     */
    private String remoteAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.user_agent
     *
     * @mbg.generated
     */
    private String userAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.oper_time
     *
     * @mbg.generated
     */
    private Date operTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.browser_type
     *
     * @mbg.generated
     */
    private String browserType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.login_type
     *
     * @mbg.generated
     */
    private String loginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.equipment
     *
     * @mbg.generated
     */
    private String equipment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umuseroperlog.logon_id
     *
     * @mbg.generated
     */
    private String logonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umuseroperlog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.resourceid
     *
     * @return the value of umuseroperlog.resourceid
     *
     * @mbg.generated
     */
    public String getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.resourceid
     *
     * @param resourceid the value for umuseroperlog.resourceid
     *
     * @mbg.generated
     */
    public void setResourceid(String resourceid) {
        this.resourceid = resourceid == null ? null : resourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.oper_type
     *
     * @return the value of umuseroperlog.oper_type
     *
     * @mbg.generated
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.oper_type
     *
     * @param operType the value for umuseroperlog.oper_type
     *
     * @mbg.generated
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.create_time
     *
     * @return the value of umuseroperlog.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.create_time
     *
     * @param createTime the value for umuseroperlog.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.user_id
     *
     * @return the value of umuseroperlog.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.user_id
     *
     * @param userId the value for umuseroperlog.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.remote_addr
     *
     * @return the value of umuseroperlog.remote_addr
     *
     * @mbg.generated
     */
    public String getRemoteAddr() {
        return remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.remote_addr
     *
     * @param remoteAddr the value for umuseroperlog.remote_addr
     *
     * @mbg.generated
     */
    public void setRemoteAddr(String remoteAddr) {
        this.remoteAddr = remoteAddr == null ? null : remoteAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.user_agent
     *
     * @return the value of umuseroperlog.user_agent
     *
     * @mbg.generated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.user_agent
     *
     * @param userAgent the value for umuseroperlog.user_agent
     *
     * @mbg.generated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.oper_time
     *
     * @return the value of umuseroperlog.oper_time
     *
     * @mbg.generated
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.oper_time
     *
     * @param operTime the value for umuseroperlog.oper_time
     *
     * @mbg.generated
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.address
     *
     * @return the value of umuseroperlog.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.address
     *
     * @param address the value for umuseroperlog.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.browser_type
     *
     * @return the value of umuseroperlog.browser_type
     *
     * @mbg.generated
     */
    public String getBrowserType() {
        return browserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.browser_type
     *
     * @param browserType the value for umuseroperlog.browser_type
     *
     * @mbg.generated
     */
    public void setBrowserType(String browserType) {
        this.browserType = browserType == null ? null : browserType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.login_type
     *
     * @return the value of umuseroperlog.login_type
     *
     * @mbg.generated
     */
    public String getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.login_type
     *
     * @param loginType the value for umuseroperlog.login_type
     *
     * @mbg.generated
     */
    public void setLoginType(String loginType) {
        this.loginType = loginType == null ? null : loginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.equipment
     *
     * @return the value of umuseroperlog.equipment
     *
     * @mbg.generated
     */
    public String getEquipment() {
        return equipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.equipment
     *
     * @param equipment the value for umuseroperlog.equipment
     *
     * @mbg.generated
     */
    public void setEquipment(String equipment) {
        this.equipment = equipment == null ? null : equipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umuseroperlog.logon_id
     *
     * @return the value of umuseroperlog.logon_id
     *
     * @mbg.generated
     */
    public String getLogonId() {
        return logonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umuseroperlog.logon_id
     *
     * @param logonId the value for umuseroperlog.logon_id
     *
     * @mbg.generated
     */
    public void setLogonId(String logonId) {
        this.logonId = logonId == null ? null : logonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umuseroperlog
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resourceid=").append(resourceid);
        sb.append(", operType=").append(operType);
        sb.append(", createTime=").append(createTime);
        sb.append(", userId=").append(userId);
        sb.append(", remoteAddr=").append(remoteAddr);
        sb.append(", userAgent=").append(userAgent);
        sb.append(", operTime=").append(operTime);
        sb.append(", address=").append(address);
        sb.append(", browserType=").append(browserType);
        sb.append(", loginType=").append(loginType);
        sb.append(", equipment=").append(equipment);
        sb.append(", logonId=").append(logonId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}