package com.example.springboot.dao;

import com.example.springboot.pojo.CfgModule;
import java.util.List;

public interface CfgModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_module
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_module
     *
     * @mbg.generated
     */
    int insert(CfgModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_module
     *
     * @mbg.generated
     */
    CfgModule selectByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_module
     *
     * @mbg.generated
     */
    List<CfgModule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CfgModule record);
}