package com.example.springboot.dao;

import com.example.springboot.pojo.HzAdjustCourseLog;
import java.util.List;

public interface HzAdjustCourseLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_adjust_course_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_adjust_course_log
     *
     * @mbg.generated
     */
    int insert(HzAdjustCourseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_adjust_course_log
     *
     * @mbg.generated
     */
    HzAdjustCourseLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_adjust_course_log
     *
     * @mbg.generated
     */
    List<HzAdjustCourseLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_adjust_course_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzAdjustCourseLog record);
}