package com.example.springboot.dao;

import com.example.springboot.pojo.HzCloudShare;
import java.util.List;

public interface HzCloudShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_cloud_share
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_cloud_share
     *
     * @mbg.generated
     */
    int insert(HzCloudShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_cloud_share
     *
     * @mbg.generated
     */
    HzCloudShare selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_cloud_share
     *
     * @mbg.generated
     */
    List<HzCloudShare> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_cloud_share
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzCloudShare record);
}