package com.example.springboot.dao;

import com.example.springboot.pojo.HzCoursewareRecord;
import java.util.List;

public interface HzCoursewareRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_courseware_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_courseware_record
     *
     * @mbg.generated
     */
    int insert(HzCoursewareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_courseware_record
     *
     * @mbg.generated
     */
    HzCoursewareRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_courseware_record
     *
     * @mbg.generated
     */
    List<HzCoursewareRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_courseware_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzCoursewareRecord record);
}