package com.example.springboot.dao;

import com.example.springboot.pojo.HzFloor;
import java.util.List;

public interface HzFloorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_floor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_floor
     *
     * @mbg.generated
     */
    int insert(HzFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_floor
     *
     * @mbg.generated
     */
    HzFloor selectByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_floor
     *
     * @mbg.generated
     */
    List<HzFloor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_floor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzFloor record);
}