package com.example.springboot.dao;

import com.example.springboot.pojo.HzHyperScheme;
import java.util.List;

public interface HzHyperSchemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_hyper_scheme
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_hyper_scheme
     *
     * @mbg.generated
     */
    int insert(HzHyperScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_hyper_scheme
     *
     * @mbg.generated
     */
    HzHyperScheme selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_hyper_scheme
     *
     * @mbg.generated
     */
    List<HzHyperScheme> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_hyper_scheme
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzHyperScheme record);
}