package com.example.springboot.dao;

import com.example.springboot.pojo.HzNoteShare;
import java.util.List;

public interface HzNoteShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_note_share
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_note_share
     *
     * @mbg.generated
     */
    int insert(HzNoteShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_note_share
     *
     * @mbg.generated
     */
    HzNoteShare selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_note_share
     *
     * @mbg.generated
     */
    List<HzNoteShare> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_note_share
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzNoteShare record);
}