package com.example.springboot.dao;

import com.example.springboot.pojo.HzQaInfo;
import java.util.List;

public interface HzQaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_qa_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_qa_info
     *
     * @mbg.generated
     */
    int insert(HzQaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_qa_info
     *
     * @mbg.generated
     */
    HzQaInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_qa_info
     *
     * @mbg.generated
     */
    List<HzQaInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_qa_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzQaInfo record);
}