package com.example.springboot.dao;

import com.example.springboot.pojo.HzSchoolYear;
import java.util.List;

public interface HzSchoolYearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_school_year
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_school_year
     *
     * @mbg.generated
     */
    int insert(HzSchoolYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_school_year
     *
     * @mbg.generated
     */
    HzSchoolYear selectByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_school_year
     *
     * @mbg.generated
     */
    List<HzSchoolYear> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_school_year
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzSchoolYear record);
}