package com.example.springboot.dao;

import com.example.springboot.pojo.HzSysNoticeDetail;
import java.util.List;

public interface HzSysNoticeDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_sys_notice_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_sys_notice_detail
     *
     * @mbg.generated
     */
    int insert(HzSysNoticeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_sys_notice_detail
     *
     * @mbg.generated
     */
    HzSysNoticeDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_sys_notice_detail
     *
     * @mbg.generated
     */
    List<HzSysNoticeDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_sys_notice_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzSysNoticeDetail record);
}