package com.example.springboot.dao;

import com.example.springboot.pojo.HzTestSchemeTmp;
import java.util.List;

public interface HzTestSchemeTmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_test_scheme_tmp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_test_scheme_tmp
     *
     * @mbg.generated
     */
    int insert(HzTestSchemeTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_test_scheme_tmp
     *
     * @mbg.generated
     */
    HzTestSchemeTmp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_test_scheme_tmp
     *
     * @mbg.generated
     */
    List<HzTestSchemeTmp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_test_scheme_tmp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzTestSchemeTmp record);
}