package com.example.springboot.dao;

import com.example.springboot.pojo.HzTeachingScheme;
import java.util.List;

public interface HzTeachingSchemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_teaching_scheme
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_teaching_scheme
     *
     * @mbg.generated
     */
    int insert(HzTeachingScheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_teaching_scheme
     *
     * @mbg.generated
     */
    HzTeachingScheme selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_teaching_scheme
     *
     * @mbg.generated
     */
    List<HzTeachingScheme> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_teaching_scheme
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzTeachingScheme record);
}