package com.example.springboot.dao;

import com.example.springboot.pojo.HzUserGroupInfo;
import java.util.List;

public interface HzUserGroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_group_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_group_info
     *
     * @mbg.generated
     */
    int insert(HzUserGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_group_info
     *
     * @mbg.generated
     */
    HzUserGroupInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_group_info
     *
     * @mbg.generated
     */
    List<HzUserGroupInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzUserGroupInfo record);
}