package com.example.springboot.dao;

import com.example.springboot.pojo.HzUserTemplateVm;
import java.util.List;

public interface HzUserTemplateVmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_template_vm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_template_vm
     *
     * @mbg.generated
     */
    int insert(HzUserTemplateVm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_template_vm
     *
     * @mbg.generated
     */
    HzUserTemplateVm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_template_vm
     *
     * @mbg.generated
     */
    List<HzUserTemplateVm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_user_template_vm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzUserTemplateVm record);
}