package com.example.springboot.dao;

import com.example.springboot.pojo.HzVmScreenShot;
import java.util.List;

public interface HzVmScreenShotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_vm_screen_shot
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_vm_screen_shot
     *
     * @mbg.generated
     */
    int insert(HzVmScreenShot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_vm_screen_shot
     *
     * @mbg.generated
     */
    HzVmScreenShot selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_vm_screen_shot
     *
     * @mbg.generated
     */
    List<HzVmScreenShot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_vm_screen_shot
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzVmScreenShot record);
}