package com.example.springboot.dao;

import com.example.springboot.pojo.HzWebupload;
import java.util.List;

public interface HzWebuploadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_webupload
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_webupload
     *
     * @mbg.generated
     */
    int insert(HzWebupload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_webupload
     *
     * @mbg.generated
     */
    HzWebupload selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_webupload
     *
     * @mbg.generated
     */
    List<HzWebupload> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_webupload
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzWebupload record);
}