package com.example.springboot.dao;

import com.example.springboot.pojo.Umrole;
import java.util.List;

public interface UmroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umrole
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umrole
     *
     * @mbg.generated
     */
    int insert(Umrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umrole
     *
     * @mbg.generated
     */
    Umrole selectByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umrole
     *
     * @mbg.generated
     */
    List<Umrole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umrole
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Umrole record);
}