package com.example.springboot.dao;

import com.example.springboot.pojo.Umspuser;
import java.util.List;

public interface UmspuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umspuser
     *
     * @mbg.generated
     */
    int insert(Umspuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umspuser
     *
     * @mbg.generated
     */
    List<Umspuser> selectAll();
}