package com.example.springboot.dao;

import com.example.springboot.pojo.Umstnav;
import java.util.List;

public interface UmstnavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umstnav
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String navid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umstnav
     *
     * @mbg.generated
     */
    int insert(Umstnav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umstnav
     *
     * @mbg.generated
     */
    Umstnav selectByPrimaryKey(String navid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umstnav
     *
     * @mbg.generated
     */
    List<Umstnav> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umstnav
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Umstnav record);
}