package com.example.springboot.dao;

import com.example.springboot.pojo.Umsystem;
import java.util.List;

public interface UmsystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsystem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String systemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsystem
     *
     * @mbg.generated
     */
    int insert(Umsystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsystem
     *
     * @mbg.generated
     */
    Umsystem selectByPrimaryKey(String systemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsystem
     *
     * @mbg.generated
     */
    List<Umsystem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsystem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Umsystem record);
}